In [1]:
#!pip install gigachat
import json
from gigachat import GigaChat
import pandas as pd

#!pip install razdel
import warnings
warnings.filterwarnings('ignore')

In [ ]:
AUTH_KEY = "=="

In [25]:
data = pd.read_csv('df_for_llm.csv')
data

,doc_id,chunk_id,is_macro,chunk_text
0,0,0,True,"""Индекс Мосбиржи -3%. Это самое большое дневно..."
1,1,0,True,"""​​Циан взлетел на апелляции Крупнейший в Росс..."
2,2,0,True,"""С 5 февраля ЕС вводит эмбарго на российские п..."
3,2,1,True,Госбюджет РФ рискует недополучить еще больше н...
4,3,0,True,"""Новый отчёт Сбера (SBER): чистая прибыль за 1..."
...,...,...,...,...
1949,1491,0,True,"""Финансовый конгресс Банка России: что важного..."
1950,1491,4,True,Этот хаб можно расположить в одной из стран Пе...
1951,1492,0,True,"""За последние 2 недели рубль ослаб почти на 8%..."
1952,1495,2,True,• Нефть дорожает По итогам вчерашних торгов ф...
1953,1499,4,True,По итогам вчерашних торгов фьючерсы на Brent п...

In [40]:
def label_data(text: str, giga: GigaChat):
    """Классификация текста через GigaChat."""

    # Формируем четкую инструкцию для модели
    prompt2 = ( "Ты — экспертный макроэкономический аналитик. Твоя задача — анализировать новости "
    "и определять динамику 18 показателей. Оценивай прямые упоминания и логические следствия. "
    "Допустимые значения изменений ТОЛЬКО ТАКИЕ: 'up', 'down', 'not stated'. "
    "Ответь строго в формате JSON без вступлений и пояснений: "
    "{"
    "\"процентная ставка\": \"тип изменения\","
    "\"ВВП\": \"тип изменения\","
    "\"инфляция\": \"тип изменения\","
    "\"безработица\": \"тип изменения\","
    "\"капитал\": \"тип изменения\","
    "\"инвестиции\": \"тип изменения\","
    "\"производство\": \"тип изменения\","
    "\"потребление\": \"тип изменения\","
    "\"численность рабочей силы\": \"тип изменения\","
    "\"сбережения\": \"тип изменения\","
    "\"заработные платы\": \"тип изменения\","
    "\"доходы населения\": \"тип изменения\","
    "\"валютный курс\": \"тип изменения\","
    "\"импорт\": \"тип изменения\","
    "\"экспорт\": \"тип изменения\","
    "\"государственные расходы\": \"тип изменения\","
    "\"государственный долг\": \"тип изменения\","
    "\"дефицит бюджета\": \"тип изменения\""
    "} "
    f"Текст новости: {text}"
)
    try:
        response = giga.chat(prompt2)
        content = response.choices[0].message.content

        # Находим JSON в ответе (на случай, если модель добавит лишний текст)
        start = content.find('{')
        end = content.rfind('}') + 1
        return json.loads(content[start:end])
    except Exception as e:
        return {"category": "Ошибка", "details": str(e)}

In [ ]:
## ТЕСТ РАЗМЕТКИ
dataset = [
    """Инфляционные процессы в российской экономике стабилизируются, полагает министр финансов Антон Силаунов. Такое мнение он высказал в письменном заявлении в преддверии заседания международного валютно-финансового комитета. Слова Силуанова приводит пресс-служба Минфина.
    «В российской экономике стабилизируются инфляционные процессы, что является залогом устойчивого и сбалансированного развития в будущем: меры экономической политики, направленные на охлаждение спроса, позволили замедлить инфляцию до минимальных с 2020 года значений – 5,59% по итогам 2025 года. При этом уровень безработицы остается на минимальных значениях (2,1% в феврале 2026 года), создаются рабочие места, растут располагаемые доходы граждан (+7,4% в 2025 году)», - отметил министр.
    По его словам, проводимая бюджетная политика поддерживает устойчивость государственных финансов. Среди стран G20 Россия занимает лидирующее место по уровню государственного долга (16,5% ВВП), а дефицит в размере 2,6% ВВП в 2025 году остается на безопасном уровне.
    «В дальнейшем фокус на укреплении устойчивости сохранится: в условиях нестабильности на сырьевых рынках ключевое внимание будет уделяться сокращению уязвимости бюджета. В этой связи планируется снижение базовой цены на нефть в бюджетном правиле с сопутствующими мероприятиями по консолидации бюджета. Такой подход поможет защитить экономику и бюджет от внешних шоков, укрепит финансовый суверенитет страны и доверие к экономической политике, а также поддержит устойчивое и сбалансированное экономическое развитие», - написал Силуанов""",
    """Банк России находится на финишной прямой перед очередным заседанием по ставке – оно состоится 24 апреля
Аналитики, опрошенные Finam.ru, в основном полагают, что Центробанк снизит ставку на очередные 0,5 п.п., до 14,5%
Влияние на курс рубля будет зависеть от того, насколько сильно решение по ставке и сигнал отклонятся от рыночных ожиданий
На рынке акций на снижение ставки в моменте обычно больше рынка реагируют компании с повышенной долговой нагрузкой
Банк России находится на финишной прямой перед очередным заседанием по ставке – оно состоится 24 апреля. На предыдущем заседании в марте регулятор снизил ставку на 0,5 п.п., до 15%. Накануне предстоящего решения инфляция преподнесла приятный сюрприз: за неделю по 13 апреля она оказалась нулевой после 0,19% на предыдущей неделе. Кроме того, согласно данным опроса «инФОМ», инфляционные ожидания россиян на год вперед в апреле снизились до 12,9% с мартовских 13,4%. Между тем, ВВП страны за два месяца показал падение на 1,8%, на что уже отдельно обращал внимание президент РФ, потребовав предложений для возобновления экономического роста.
Аналитики, опрошенные Finam.ru, в основном полагают, что Центробанк снизит ставку на очередные 0,5 п.п., до 14,5%. Что мешает смягчить политику еще больше, какими будут последствия решения регулятора для рубля и различных классов активов, удастся ли властям не допустить переохлаждения экономики и какую роль в этом могут сыграть действия ЦБ? Finam.ru подготовил обзор.
Смягчение политики ЦБ влечет за собой дальнейшее снижение доходности по депозитам. Однако на рынке облигаций еще остаются возможности зафиксировать высокую доходность на длительный срок.""",
"""Инфляционные ожидания россиян на год вперед в апреле 2026 года снизились до 12,9% с 13,4% в предыдущем месяце, свидетельствуют итоги исследования ООО «инФОМ», опубликованные Банком России.
Показатель опустился ниже 13% впервые с октября 2025 года.
При этом наблюдаемая инфляция в апреле снизилась до 14,6% с 15,6% в марте."""]

# Запуск основной логики
if __name__ == "__main__":
    print("🚀 Начинаю разметку через GigaChat...")

    results = []

    # verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
    with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
        for i, text in enumerate(dataset, 1):
            label = label_data(text, giga)
            label['original_text'] = text
            results.append(label)
    df = pd.DataFrame(results)

In [7]:
df

,category,details,original_text,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,...,численность рабочей силы,сбережения,заработные платы,доходы населения,валютный курс,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета
0,Ошибка,[WinError 10054] Удаленный хост принудительно ...,Инфляционные процессы в российской экономике с...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Банк России находится на финишной прямой перед...,down,down,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated
2,NaN,NaN,Инфляционные ожидания россиян на год вперед в ...,not stated,not stated,down,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated

## РАЗМЕТИМ ПЕРВЫЕ 100 ПРИМЕРОВ

In [ ]:
print("🚀 Начинаю разметку через GigaChat...")
dataset = list(data['chunk_text'])[:100]
results = []

# verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
    for i, text in enumerate(dataset, 1):
        print(f'Обработка документа {i}...')
        label = label_data(text, giga)
        label['doc_id'] = data.iloc[i, 0]
        label['chunk_id'] = data.iloc[i, 1]
        label['original_text'] = text

        results.append(label)

🚀 Начинаю разметку через GigaChat...
Обработка документа 1...
Обработка документа 2...
Обработка документа 3...
Обработка документа 4...
Обработка документа 5...
Обработка документа 6...
Обработка документа 7...
Обработка документа 8...
Обработка документа 9...
Обработка документа 10...
Обработка документа 11...
Обработка документа 12...
Обработка документа 13...
Обработка документа 14...
Обработка документа 15...
Обработка документа 16...
Обработка документа 17...
Обработка документа 18...
Обработка документа 19...
Обработка документа 20...
Обработка документа 21...
Обработка документа 22...
Обработка документа 23...
Обработка документа 24...
Обработка документа 25...
Обработка документа 26...
Обработка документа 27...
Обработка документа 28...
Обработка документа 29...
Обработка документа 30...
Обработка документа 31...
Обработка документа 32...
Обработка документа 33...
Обработка документа 34...
Обработка документа 35...
Обработка документа 36...
Обработка документа 37...
Обработка документа 38...
Обработка документа 39...
Обработка документа 40...
Обработка документа 41...
Обработка документа 42...
Обработка документа 43...
Обработка документа 44...
Обработка документа 45...
Обработка документа 46...
Обработка документа 47...
Обработка документа 48...
Обработка документа 49...
Обработка документа 50...
Обработка документа 51...
Обработка документа 52...
Обработка документа 53...
Обработка документа 54...
Обработка документа 55...
Обработка документа 56...
Обработка документа 57...
Обработка документа 58...
Обработка документа 59...
Обработка документа 60...
Обработка документа 61...
Обработка документа 62...
Обработка документа 63...
Обработка документа 64...
Обработка документа 65...
Обработка документа 66...
Обработка документа 67...
Обработка документа 68...
Обработка документа 69...
Обработка документа 70...
Обработка документа 71...
Обработка документа 72...
Обработка документа 73...
Обработка документа 74...
Обработка документа 75...
Обработка документа 76...
Обработка документа 77...
Обработка документа 78...
Обработка документа 79...
Обработка документа 80...
Обработка документа 81...
Обработка документа 82...
Обработка документа 83...
Обработка документа 84...
Обработка документа 85...
Обработка документа 86...
Обработка документа 87...
Обработка документа 88...
Обработка документа 89...
Обработка документа 90...
Обработка документа 91...
Обработка документа 92...
Обработка документа 93...
Обработка документа 94...
Обработка документа 95...
Обработка документа 96...
Обработка документа 97...
Обработка документа 98...
Обработка документа 99...
Обработка документа 100...

In [58]:
results

[{'процентная ставка': 'not stated',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'down',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(1),
  'chunk_id': np.int64(0),
  'original_text': '"Индекс Мосбиржи -3%. Это самое большое дневное падение индекса с 7 октября. #шок_новости На фото - перфоманс акций индекса широкого рынка Мосбиржи за сегодня. "'},
 {'процентная ставка': 'not stated',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(2),
  'chunk_id': np.int64(0),
  'original_text': '"\u200b\u200bЦиан взлетел на апелляции Крупнейший в России сервис для продажи и аренды недвижимости сегодня в топе подорожавших эмитентов на Мосбирже. К 13.14 мск бумаги торговались 500,6 руб. (+9,54% с начала торгов). Ранее стало известно, что компания подала апелляцию на решение Нью-Йоркской фондовой биржи (NYSE) о делистинге американских депозитарных расписок компании. Процедура делистинга будет приостановлена, пока не рассмотрят апелляцию. «Компания была и остается полностью соответствующей всем применимыми обязательствам по отчетности и качественным и количественным критериям листинга NYSE», — говорится в сообщении компании. Кроме NYSE еще и биржа Nasdaq также уведомила о делистинге с 24 марта акций ряда компаний, основной бизнес находится в России. Уведомления получили Headhunter, Ozon, Qiwi, Яндекс. Эти компании также подали апелляции. #новости"'},
 {'процентная ставка': 'not stated',
  'ВВП': 'down',
  'инфляция': 'up',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'down',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'down',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'down',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'up',
  'doc_id': np.int64(2),
  'chunk_id': np.int64(1),
  'original_text': '"С 5 февраля ЕС вводит эмбарго на российские поставки нефтепродуктов морем. Более того, европейские регуляторы обсуждают параметры потолка цен на нефтепродукты. Например, стоимость дизельного топлива хотят ограничить на уровне $100/барр. Россия — крупный экспортер дизельного топлива (15% мирового предложения), особенно для еврозоны, куда она направляла 80% поставок. Эти санкции могут быть более разрушительными, чем декабрьские ограничения на сырую нефть. Дело в том, что поставки сырой нефти удалось перенаправить в Индию и Китай. Но дизельное топливо туда не отправишь, потому что Индия и Китай сами являются крупными экспортерами этого сырья. Теперь придется искать новых покупателей, но кто ими может стать, непонятно. Госбюджет РФ рискует недополучить еще больше нефтегазовых доходов (в январе недополучит ок. 54,5 млрд руб.), из-за чего дефицит госбюджета может еще сильнее расшириться.'},
 {'процентная ставка': 'not stated',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'up',
  'doc_id': np.int64(3),
  'chunk_id': np.int64(0),
  'original_text': 'Госбюджет РФ рискует недополучить еще больше нефтегазовых доходов (в январе недополучит ок. 54,5 млрд руб.), из-за чего дефицит госбюджета может еще сильнее расшириться. #макро #россия #сырье"'},
 {'процентная ставка': 'не указано',
  'ВВП': 'не указано',
  'инфляция': 'не указано',
  'безработица': 'не указано',
  'капитал': 'рост портфеля жилищного кредитования (+3.5%)',
  'инвестиции': 'не указано',
  'производство': 'не указано',
  'потребление': 'не указано',
  'численность рабочей силы': 'не указано',
  'сбережения': 'не указано',
  'заработные платы': 'не указано',
  'доходы населения': 'не указано',
  'валютный курс': 'не указано',
  'импорт': 'не указано',
  'экспорт': 'не указано',
  'государственные расходы': 'не указано',
  'государственный долг': 'не указано',
  'дефицит бюджета': 'не указано',
  'doc_id': np.int64(4),
  'chunk_id': np.int64(0),
  'original_text': '"Новый отчёт Сбера (SBER): чистая прибыль за 10 месяцев 2023 составила 1.26 трлн руб. Каким будет дивиденд? #аналитика Главное из отчета за 10 месяцев по РПБУ: • портфель жилищных кредитов вырос на 3.5% м/м, объём превысил 9.7 трлн руб. • корпоративный кредитный портфель +0.9% м/м, розничный +2.7% м/м • доля просроченной задолженности на уровне 2% • операционные расходы выросли на 27% г/г с низкой базы 2022 • рентабельность капитала (ROE) за 10 мес. на уровне 25.3% По прогнозам источников РДВ, чистая прибыль Сбера по итогам года превысит 1.5 трлн руб., а расчётный дивиденд превысит 33 рубля на акцию, доходность 11.78% к текущей цене. "'},
 {'процентная ставка': 'not stated',
  'ВВП': 'down',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'down',
  'инвестиции': 'not stated',
  'производство': 'down',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'down',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(4),
  'chunk_id': np.int64(1),
  'original_text': '"\u200b\u200bГазпром: почему дивидендов не будет? Газпром опубликовал крайне слабый отчет по МСФО за 2022 год. Подкачало второе полугодие на фоне теплой зимы в Европе и снижения спроса на ключевом экспортном рынке (европейском). Компания зафиксировала убыток в размере 1,2 трлн рублей (в первом полугодии была прибыль в размере 2,5 трлн рублей). В связи с убытками во второй половине 2022-го совет директоров компании принял решение не рекомендовать выплату финальных дивидендов за прошлый год. Напомним, что консенсус-прогноз предполагал дивиденды Газпрома за второе полугодие 2022-го в среднем на уровне 7,62 руб./акцию. Мы ждали чуть больше при позитивном развитии событий — 10 руб./акцию. Отметим, что свежий отчет Газпрома — единственный подробный отчет за 2022 год. Поэтому отследить динамику показателей в течение прошлого года довольно сложно.'},
 {'category': 'Ошибка',
  'details': 'Invalid control character at: line 3 column 21 (char 57)',
  'doc_id': np.int64(5),
  'chunk_id': np.int64(0),
  'original_text': 'Отметим, что свежий отчет Газпрома — единственный подробный отчет за 2022 год. Поэтому отследить динамику показателей в течение прошлого года довольно сложно. За весь год динамика продаж в разных сегментах бизнеса весьма позитивная, но предполагаем, что это связано в большей степени с успехами именно первой половины 2022-го. За 2022 год внешние продажи газа +12,8% г/г (до 7,73 трлн руб.); внешние продажи нефти +19,4% г/г (до 3,39 трлн руб.); внешние продажи электроэнергии +1,3% г/г (до 556,7 млрд руб.); суммарные межсегментные продажи +23,4% г/г (до 675,8 млрд руб.). Добавим, что уровень долговой нагрузки у компании увеличился. С конца первого полугодия 2022-го до конца 2022 года чистый долг/EBITDA вырос с 0,23х до 1,1х.      Что с нашей арбитражной идеей К сожалению, реализовался негативный сценарий — финальных дивидендов от Газпрома за 2022 год не будет.'},
 {'процентная ставка': 'not stated',
  'ВВП': 'down',
  'инфляция': 'up',
  'безработица': 'not stated',
  'капитал': 'down',
  'инвестиции': 'down',
  'производство': 'down',
  'потребление': 'down',
  'численность рабочей силы': 'not stated',
  'сбережения': 'down',
  'заработные платы': 'down',
  'доходы населения': 'down',
  'валютный курс': 'up',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(6),
  'chunk_id': np.int64(0),
  'original_text': '"Окно закрывается. С начала СВО физлица вывели на свои зарубежные счета $43 млрд. #цифры Только за май по официальной статистике ЦБ россияне вывели из страны $1.8 млрд. Qiwi (QIWI) ограничил снятие наличных и вывод средств с qiwi-кошельков в другие банки по предписанию ЦБ:  "'},
 {'процентная ставка': 'not stated',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'up',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(6),
  'chunk_id': np.int64(2),
  'original_text': '"\u200b\u200bДивидендам от сталеваров быть? Сегодня, 11 января, генеральный директор Северстали Александр Шевелев сообщил, что совет директоров компании на ближайшем заседании может рассмотреть вопрос выплаты дивидендов за 2023 год. Это спровоцировало рост котировок российских сталелитейных компаний. Напомним, что Северсталь, ММК и НЛМК не платили дивиденды с конца 2021-го—начала 2022-го. Потенциальный возврат компаний к дивидендным выплатам повышает их инвестиционную привлекательность, в связи с чем и наблюдается рост котировок. Все три упомянутые компании платят дивиденды, исходя из величины свободного денежного потока (FCF). Если на дивиденды за 2023 год они направят 100% FCF, то, по нашим оценкам:   дивиденд по акциям Северстали может составить 122 руб./акцию (доходность 8%);  дивиденды ММК — 3 руб./акцию (5%);  дивиденд НЛМК — 21 руб./акцию (11%).'},
 {'процентная ставка': 'не указано',
  'ВВП': 'не указано',
  'инфляция': 'не указано',
  'безработица': 'не указано',
  'капитал': 'не указано',
  'инвестиции': 'не указано',
  'производство': 'не указано',
  'потребление': 'не указано',
  'численность рабочей силы': 'не указано',
  'сбережения': 'не указано',
  'заработные платы': 'не указано',
  'доходы населения': 'не указано',
  'валютный курс': 'не указано',
  'импорт': 'не указано',
  'экспорт': 'не указано',
  'государственные расходы': 'не указано',
  'государственный долг': 'не указано',
  'дефицит бюджета': 'не указано',
  'doc_id': np.int64(7),
  'chunk_id': np.int64(0),
  'original_text': 'В теории это позволяет компаниям направить на выплату дивидендов более 100% FCF. В конце 2023 года УК Тинькофф Капитал запустила биржевой фонд БПИФ «Тинькофф Дивидендные акции». При его формировании, в частности, была сделана ставка на возобновление дивидендов сталеварами в 2024 году. Сейчас суммарная доля акций Северстали, ММК и НЛМК в данном фонде составляет 17,5%. #россия"'},
 {'процентная ставка': 'not stated',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'down',
  'экспорт': 'down',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(7),
  'chunk_id': np.int64(2),
  'original_text': '"Экспорт и импорт Китая продолжает снижаться, а Moody’s понижает кредитные рейтинги банков из США Главные новости зарубежных рынков к этому утру Фондовые индексы США выросли в понедельник S&P 500 прибавил 0,9%, высокотехнологичный Nasdaq — 0,6%, а индекс Dow Jones — 1,2%. Все благодаря публикации более сильных, чем ожидалось, финансовых результатов американских компаний за второй квартал 2023 года. По данным Fundstrat, 85% компаний из списка S&P 500 уже представили свои квартальные отчеты: 81% превышают оценки по прибыли в среднем на 7%, а 64% превышают оценки по выручке в среднем на 3%.'},
 {'процентная ставка': 'not stated',
  'ВВП': 'down',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'down',
  'экспорт': 'down',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(7),
  'chunk_id': np.int64(4),
  'original_text': 'Китай сообщает о двузначном падении экспорта и импорта в июле По данным Reuters, в прошлом месяце китайский импорт сократился на 12,4% в годовом исчислении, против прогнозируемого экспертами снижения на 5%. В свою очередь, экспорт из Китая в июле сократился на 14,5%, что больше ожидаемого снижения на 12,5% и падения на 12,4% в предыдущем месяце. Между тем, экономика Китая росла вялыми темпами во втором квартале 2023 года из-за ослабления спроса внутри страны и за рубежом, что побудило высших руководителей обещать дальнейшую политическую поддержку, а аналитиков понижать свои прогнозы относительно роста китайской экономики в этом году.'},
 {'процентная ставка': 'up',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(8),
  'chunk_id': np.int64(0),
  'original_text': 'В Moody’s также предупредили, что в ближайшей перспективе могут быть понижены рейтинги и для крупных американских кредиторов, включая US Bancorp, Bank of New York Mellon, State Street и Truist Financial Corporation на фоне общего давления на отрасль. Инвесторы, потрясенные крахом банков в США и Европе в этом году, внимательно следят за признаками стресса в отрасли, поскольку рост процентных ставок вынуждает банки платить больше за депозиты и увеличивает стоимость финансирования. В то же время более высокие ставки снижают стоимость активов кредитных организаций и затрудняют рефинансирование долгов заемщиками, что потенциально ведет к ослаблению баланса банков, замечает Bloomberg. #новости"'},
 {'процентная ставка': 'not stated',
  'ВВП': 'not stated',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'not stated',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(8),
  'chunk_id': np.int64(1),
  'original_text': '" Техи отчитались — рынки растут  Главные новости зарубежных рынков к этому утру ️Фондовые индексы США выросли в четверг S&P 500 прибавил примерно 2%, высокотехнологичный Nasdaq — 2,4%, а индекс Dow Jones — 1,6%. Сильные квартальные отчеты американских технологических гигантов поддержали рост основных фондовых индексов США. Между тем акции региональных банков несколько стабилизировались после недавнего падения на фоне проблем First Republic Bank с удержанием депозитов. ️Рынки Азии преимущественно растут Широкий индекс акций Азии (за исключением Японии) MSCI AC Asia ex Japan Index вырос сегодня на 0,5%, японский Nikkei прибавил 0,9%, южнокорейский Kospi увеличился на 0,1%, китайский Shanghai Composite и гонконгский Hang Seng подорожали на 0,7% и 0,9% соответственно, а сингапурский STI снизился на 0,2%.'},
 {'процентная ставка': 'not stated',
  'ВВП': 'down',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'down',
  'производство': 'not stated',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(8),
  'chunk_id': np.int64(2),
  'original_text': 'Рынки Азиатско-Тихоокеанского региона в значительной степени выросли в пятницу благодаря сильным корпоративным отчетам американских IT-гигантов. Настроение инвесторов в Азии поддержало решение банка Японии оставить без изменений свою денежно-кредитную политику. ️Экономический рост США резко замедлился в первом квартале 2023 года По данным Министерства торговли США, валовой внутренний продукт страны в январе-марте 2023 года вырос на 1,1% в годовом исчислении по сравнению с ростом на 2,6% в предыдущем квартале. Опрошенные Dow Jones экономисты ожидали квартального роста ВВП США на уровне 2%. В отчете Министерства торговли США говорится, что замедление роста ВВП произошло из-за сокращения предприятиями своих расходов, а также снижения объема инвестиций в товарно-материальные запасы.'},
 {'процентная ставка': 'up',
  'ВВП': 'down',
  'инфляция': 'not stated',
  'безработица': 'not stated',
  'капитал': 'not stated',
  'инвестиции': 'down',
  'производство': 'down',
  'потребление': 'not stated',
  'численность рабочей силы': 'not stated',
  'сбережения': 'not stated',
  'заработные платы': 'not stated',
  'доходы населения': 'not stated',
  'валютный курс': 'not stated',
  'импорт': 'not stated',
  'экспорт': 'not stated',
  'государственные расходы': 'not stated',
  'государственный долг': 'not stated',
  'дефицит бюджета': 'not stated',
  'doc_id': np.int64(8),
  'chunk_id': np.int64(3),

In [63]:
df100 = pd.DataFrame(results)
df100

,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,потребление,численность рабочей силы,сбережения,...,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета,doc_id,chunk_id,original_text,category,details
0,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,1,0,"""Индекс Мосбиржи -3%. Это самое большое дневно...",NaN,NaN
1,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,2,0,"""​​Циан взлетел на апелляции Крупнейший в Росс...",NaN,NaN
2,not stated,down,up,not stated,not stated,not stated,down,not stated,not stated,not stated,...,not stated,down,not stated,not stated,up,2,1,"""С 5 февраля ЕС вводит эмбарго на российские п...",NaN,NaN
3,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,up,3,0,Госбюджет РФ рискует недополучить еще больше н...,NaN,NaN
4,не указано,не указано,не указано,не указано,рост портфеля жилищного кредитования (+3.5%),не указано,не указано,не указано,не указано,не указано,...,не указано,не указано,не указано,не указано,не указано,4,0,"""Новый отчёт Сбера (SBER): чистая прибыль за 1...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,not stated,down,not stated,not stated,not stated,down,down,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,51,5,"Коммерческая недвижимость в США и ЕС, которая ...",NaN,NaN
96,not stated,down,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,52,0,Никто из опрошенных теперь не ожидает сильного...,NaN,NaN
97,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,...,не указано,не указано,не указано,не указано,не указано,57,1,"""​​ВТБ с рекордными убытками. Бумаги падают, д...",NaN,NaN
98,up,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,58,2,При этом регулярная прибыль смогла показать ро...,NaN,NaN
99,down,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,59,0,Однако с учетом денежных средств на счетах эск...,NaN,NaN

### Видим проблему с промптом, не всегда выдается что надо, но в целом все можно поправить руками

In [ ]:
df100['процентная ставка'].value_counts()

процентная ставка
not stated    70
up            10
down           8
не указано     7
Name: count, dtype: int64

In [ ]:
df100['капитал'].value_counts()

капитал
not stated                                      70
up                                              12
down                                             7
не указано                                       5
рост портфеля жилищного кредитования (+3.5%)     1
Name: count, dtype: int64

## 2-АЯ ЧАСТЬ РАЗМЕТКИ(ОТ 100 ДО 449)

In [ ]:
print("🚀 Начинаю разметку через GigaChat...")
dataset_100_449 = list(data['chunk_text'])[100:449]
results_2 = []

# verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
    for i, text in enumerate(dataset_100_449, 1):
        print(f'Обработка документа {i + 100}...')
        label = label_data(text, giga)
        label['doc_id'] = data.iloc[i + 100, 0]
        label['chunk_id'] = data.iloc[i + 100, 1]
        label['original_text'] = text

        results_2.append(label)

🚀 Начинаю разметку через GigaChat...
Обработка документа 101...
Обработка документа 102...
Обработка документа 103...
Обработка документа 104...
Обработка документа 105...
Обработка документа 106...
Обработка документа 107...
Обработка документа 108...
Обработка документа 109...
Обработка документа 110...
Обработка документа 111...
Обработка документа 112...
Обработка документа 113...
Обработка документа 114...
Обработка документа 115...
Обработка документа 116...
Обработка документа 117...
Обработка документа 118...
Обработка документа 119...
Обработка документа 120...
Обработка документа 121...
Обработка документа 122...
Обработка документа 123...
Обработка документа 124...
Обработка документа 125...
Обработка документа 126...
Обработка документа 127...
Обработка документа 128...
Обработка документа 129...
Обработка документа 130...
Обработка документа 131...
Обработка документа 132...
Обработка документа 133...
Обработка документа 134...
Обработка документа 135...
Обработка документа 136...
Обработка документа 137...
Обработка документа 138...
Обработка документа 139...
Обработка документа 140...
Обработка документа 141...
Обработка документа 142...
Обработка документа 143...
Обработка документа 144...
Обработка документа 145...
Обработка документа 146...
Обработка документа 147...
Обработка документа 148...
Обработка документа 149...
Обработка документа 150...
Обработка документа 151...
Обработка документа 152...
Обработка документа 153...
Обработка документа 154...
Обработка документа 155...
Обработка документа 156...
Обработка документа 157...
Обработка документа 158...
Обработка документа 159...
Обработка документа 160...
Обработка документа 161...
Обработка документа 162...
Обработка документа 163...
Обработка документа 164...
Обработка документа 165...
Обработка документа 166...
Обработка документа 167...
Обработка документа 168...
Обработка документа 169...
Обработка документа 170...
Обработка документа 171...
Обработка документа 172...
Обработка документа 173...
Обработка документа 174...
Обработка документа 175...
Обработка документа 176...
Обработка документа 177...
Обработка документа 178...
Обработка документа 179...
Обработка документа 180...
Обработка документа 181...
Обработка документа 182...
Обработка документа 183...
Обработка документа 184...
Обработка документа 185...
Обработка документа 186...
Обработка документа 187...
Обработка документа 188...
Обработка документа 189...
Обработка документа 190...
Обработка документа 191...
Обработка документа 192...
Обработка документа 193...
Обработка документа 194...
Обработка документа 195...
Обработка документа 196...
Обработка документа 197...
Обработка документа 198...
Обработка документа 199...
Обработка документа 200...
Обработка документа 201...
Обработка документа 202...
Обработка документа 203...
Обработка документа 204...
Обработка документа 205...
Обработка документа 206...
Обработка документа 207...
Обработка документа 208...
Обработка документа 209...
Обработка документа 210...
Обработка документа 211...
Обработка документа 212...
Обработка документа 213...
Обработка документа 214...
Обработка документа 215...
Обработка документа 216...
Обработка документа 217...
Обработка документа 218...
Обработка документа 219...
Обработка документа 220...
Обработка документа 221...
Обработка документа 222...
Обработка документа 223...
Обработка документа 224...
Обработка документа 225...
Обработка документа 226...
Обработка документа 227...
Обработка документа 228...
Обработка документа 229...
Обработка документа 230...
Обработка документа 231...
Обработка документа 232...
Обработка документа 233...
Обработка документа 234...
Обработка документа 235...
Обработка документа 236...
Обработка документа 237...
Обработка документа 238...
Обработка документа 239...
Обработка документа 240...
Обработка документа 241...
Обработка документа 242...
Обработка документа 243...
Обработка документа 244...
Обработка документа 245...
Обработка документа 246...
Обработка документа 247...
Обработка документа 248...
Обработка документа 249...
Обработка документа 250...
Обработка документа 251...
Обработка документа 252...
Обработка документа 253...
Обработка документа 254...
Обработка документа 255...
Обработка документа 256...
Обработка документа 257...
Обработка документа 258...
Обработка документа 259...
Обработка документа 260...
Обработка документа 261...
Обработка документа 262...
Обработка документа 263...
Обработка документа 264...
Обработка документа 265...
Обработка документа 266...
Обработка документа 267...
Обработка документа 268...
Обработка документа 269...
Обработка документа 270...
Обработка документа 271...
Обработка документа 272...
Обработка документа 273...
Обработка документа 274...
Обработка документа 275...
Обработка документа 276...
Обработка документа 277...
Обработка документа 278...
Обработка документа 279...
Обработка документа 280...
Обработка документа 281...
Обработка документа 282...
Обработка документа 283...
Обработка документа 284...
Обработка документа 285...
Обработка документа 286...
Обработка документа 287...
Обработка документа 288...
Обработка документа 289...
Обработка документа 290...
Обработка документа 291...
Обработка документа 292...
Обработка документа 293...
Обработка документа 294...
Обработка документа 295...
Обработка документа 296...
Обработка документа 297...
Обработка документа 298...
Обработка документа 299...
Обработка документа 300...
Обработка документа 301...
Обработка документа 302...
Обработка документа 303...
Обработка документа 304...
Обработка документа 305...
Обработка документа 306...
Обработка документа 307...
Обработка документа 308...
Обработка документа 309...
Обработка документа 310...
Обработка документа 311...
Обработка документа 312...
Обработка документа 313...
Обработка документа 314...
Обработка документа 315...
Обработка документа 316...
Обработка документа 317...
Обработка документа 318...
Обработка документа 319...
Обработка документа 320...
Обработка документа 321...
Обработка документа 322...
Обработка документа 323...
Обработка документа 324...
Обработка документа 325...
Обработка документа 326...
Обработка документа 327...
Обработка документа 328...
Обработка документа 329...
Обработка документа 330...
Обработка документа 331...
Обработка документа 332...
Обработка документа 333...
Обработка документа 334...
Обработка документа 335...
Обработка документа 336...
Обработка документа 337...
Обработка документа 338...
Обработка документа 339...
Обработка документа 340...
Обработка документа 341...
Обработка документа 342...
Обработка документа 343...
Обработка документа 344...
Обработка документа 345...
Обработка документа 346...
Обработка документа 347...
Обработка документа 348...
Обработка документа 349...
Обработка документа 350...
Обработка документа 351...
Обработка документа 352...
Обработка документа 353...
Обработка документа 354...
Обработка документа 355...
Обработка документа 356...
Обработка документа 357...
Обработка документа 358...
Обработка документа 359...
Обработка документа 360...
Обработка документа 361...
Обработка документа 362...
Обработка документа 363...
Обработка документа 364...
Обработка документа 365...
Обработка документа 366...
Обработка документа 367...
Обработка документа 368...
Обработка документа 369...
Обработка документа 370...
Обработка документа 371...
Обработка документа 372...
Обработка документа 373...
Обработка документа 374...
Обработка документа 375...
Обработка документа 376...
Обработка документа 377...
Обработка документа 378...
Обработка документа 379...
Обработка документа 380...
Обработка документа 381...
Обработка документа 382...
Обработка документа 383...
Обработка документа 384...
Обработка документа 385...
Обработка документа 386...
Обработка документа 387...
Обработка документа 388...
Обработка документа 389...
Обработка документа 390...
Обработка документа 391...
Обработка документа 392...
Обработка документа 393...
Обработка документа 394...
Обработка документа 395...
Обработка документа 396...
Обработка документа 397...
Обработка документа 398...
Обработка документа 399...
Обработка документа 400...
Обработка документа 401...
Обработка документа 402...
Обработка документа 403...
Обработка документа 404...
Обработка документа 405...
Обработка документа 406...
Обработка документа 407...
Обработка документа 408...
Обработка документа 409...
Обработка документа 410...
Обработка документа 411...
Обработка документа 412...
Обработка документа 413...
Обработка документа 414...
Обработка документа 415...
Обработка документа 416...
Обработка документа 417...
Обработка документа 418...
Обработка документа 419...
Обработка документа 420...
Обработка документа 421...
Обработка документа 422...
Обработка документа 423...
Обработка документа 424...
Обработка документа 425...
Обработка документа 426...
Обработка документа 427...
Обработка документа 428...
Обработка документа 429...
Обработка документа 430...
Обработка документа 431...
Обработка документа 432...
Обработка документа 433...
Обработка документа 434...
Обработка документа 435...
Обработка документа 436...
Обработка документа 437...
Обработка документа 438...
Обработка документа 439...
Обработка документа 440...
Обработка документа 441...
Обработка документа 442...
Обработка документа 443...
Обработка документа 444...
Обработка документа 445...
Обработка документа 446...
Обработка документа 447...
Обработка документа 448...
Обработка документа 449...

KeyboardInterrupt:

In [ ]:
df449 = pd.DataFrame(results_2)
df449_full = pd.concat([df100, df449], axis=0)

In [78]:
df449_full_new = df449_full.drop(['category', 'details', 'государственные доходы', 'налоговые поступления'], axis=1)

In [312]:
## -30 ДАННЫХ
df449_full_good = df449_full_new.dropna()

## НЕМНОГО ПОФИКСИМ ОТВЕТ

In [313]:
# процентная ставка
df449_full_good['процентная ставка'].value_counts()

процентная ставка
not stated                    311
up                             67
down                           24
не указано                     18
up or down (не определено)      1
Name: count, dtype: int64

In [314]:
df449_full_good.loc[df449_full_good['процентная ставка'] == 'не указано', 'процентная ставка'] = 'not stated'
df449_full_good.loc[df449_full_good['процентная ставка'] == 'up or down (не определено)', 'процентная ставка'] = 'not stated'

In [315]:
df449_full_good['процентная ставка'].value_counts()

процентная ставка
not stated    330
up             67
down           24
Name: count, dtype: int64

In [316]:
## ВВП
df449_full_good['ВВП'].value_counts()

ВВП
not stated    323
down           65
не указано     18
up             15
Name: count, dtype: int64

In [317]:
df449_full_good.loc[df449_full_good['ВВП'] == 'не указано', 'ВВП'] = 'not stated'

In [318]:
df449_full_good['ВВП'].value_counts()

ВВП
not stated    341
down           65
up             15
Name: count, dtype: int64

In [319]:
## безработица
df449_full_good['безработица'].value_counts()

безработица
not stated    391
не указано     19
up              8
down            3
Name: count, dtype: int64

In [320]:
df449_full_good.loc[df449_full_good['безработица'] == 'не указано', 'безработица'] = 'not stated'

In [321]:
df449_full_good['безработица'].value_counts()

безработица
not stated    410
up              8
down            3
Name: count, dtype: int64

In [322]:
## капитал
df449_full_good['капитал'].value_counts()

капитал
not stated                                             343
up                                                      37
down                                                    24
не указано                                              15
рост портфеля жилищного кредитования (+3.5%)             1
up» (благодаря запасу капитала банковского сектора)      1
Name: count, dtype: int64

In [ ]:
df449_full_good.loc[df449_full_good['капитал'] == 'не указано', 'капитал'] = 'not stated'

df449_full_good.loc[df449_full_good['капитал'] == 'рост портфеля жилищного кредитования (+3.5%)', 'капитал'] = 'up'
df449_full_good.loc[df449_full_good['капитал'] == 'up» (благодаря запасу капитала банковского сектора)', 'капитал'] = 'up'

In [324]:
df449_full_good['капитал'].value_counts()

капитал
not stated    358
up             39
down           24
Name: count, dtype: int64

In [325]:
# инвестиции
df449_full_good['инвестиции'].value_counts()

инвестиции
not stated    350
down           27
up             25
не указано     19
Name: count, dtype: int64

In [326]:
df449_full_good.loc[df449_full_good['инвестиции'] == 'не указано', 'инвестиции'] = 'not stated'

In [327]:
df449_full_good['инвестиции'].value_counts()

инвестиции
not stated    369
down           27
up             25
Name: count, dtype: int64

In [328]:
# производство
df449_full_good['производство'].value_counts()

производство
not stated                          300
down                                 72
up                                   30
не указано                           18
down», (электростанции РусГидро)      1
Name: count, dtype: int64

In [329]:
df449_full_good.loc[df449_full_good['производство'] == 'не указано', 'производство'] = 'not stated'
df449_full_good.loc[df449_full_good['производство'] == 'down», (электростанции РусГидро)', 'производство'] = 'down'

In [ ]:
df449_full_good['производство'].value_counts()

производство
not stated    318
down           73
up             30
Name: count, dtype: int64

In [331]:
# потребление
df449_full_good['потребление'].value_counts()

потребление
not stated    382
не указано     18
down           13
up              8
Name: count, dtype: int64

In [332]:
df449_full_good.loc[df449_full_good['потребление'] == 'не указано', 'потребление'] = 'not stated'

In [333]:
df449_full_good['потребление'].value_counts()

потребление
not stated    400
down           13
up              8
Name: count, dtype: int64

In [334]:
# численность рабочей силы
df449_full_good['численность рабочей силы'].value_counts()

численность рабочей силы
not stated    393
не указано     19
down            5
up              4
Name: count, dtype: int64

In [335]:
df449_full_good.loc[df449_full_good['численность рабочей силы'] == 'не указано', 'численность рабочей силы'] = 'not stated'

In [336]:
df449_full_good['численность рабочей силы'].value_counts()

численность рабочей силы
not stated    412
down            5
up              4
Name: count, dtype: int64

In [337]:
# сбережения
df449_full_good['сбережения'].value_counts()

сбережения
not stated    396
не указано     19
down            3
up              3
Name: count, dtype: int64

In [338]:
df449_full_good.loc[df449_full_good['сбережения'] == 'не указано', 'сбережения'] = 'not stated'

In [339]:
df449_full_good['сбережения'].value_counts()

сбережения
not stated    415
down            3
up              3
Name: count, dtype: int64

In [340]:
# заработные платы
df449_full_good['заработные платы'].value_counts()

заработные платы
not stated    383
не указано     19
down           11
up              8
Name: count, dtype: int64

In [341]:
df449_full_good.loc[df449_full_good['заработные платы'] == 'не указано', 'заработные платы'] = 'not stated'

In [342]:
df449_full_good['заработные платы'].value_counts()

заработные платы
not stated    402
down           11
up              8
Name: count, dtype: int64

In [343]:
# доходы населения
df449_full_good['доходы населения'].value_counts()

доходы населения
not stated                                      374
down                                             18
не указано                                       18
up                                               10
не явно увеличатся, но не уточнено конкретно      1
Name: count, dtype: int64

In [344]:
df449_full_good.loc[df449_full_good['доходы населения'] == 'не указано', 'доходы населения'] = 'not stated'
df449_full_good.loc[df449_full_good['доходы населения'].apply(lambda x: x.split()[0]) == 'не', 'доходы населения'] = 'up'

In [345]:
df449_full_good['доходы населения'].value_counts()

доходы населения
not stated    392
down           18
up             11
Name: count, dtype: int64

In [346]:
# валютный курс
df449_full_good['валютный курс'].value_counts()

валютный курс
not stated                   313
down                          49
up                            42
не указано                    16
up», (доллар укрепляется)      1
Name: count, dtype: int64

In [347]:
df449_full_good.loc[df449_full_good['валютный курс'] == 'не указано', 'валютный курс'] = 'not stated'
df449_full_good.loc[df449_full_good['валютный курс'] == 'up», (доллар укрепляется)', 'валютный курс'] = 'up'

In [348]:
df449_full_good['валютный курс'].value_counts()

валютный курс
not stated    329
down           49
up             43
Name: count, dtype: int64

In [349]:
# импорт
df449_full_good['импорт'].value_counts()

импорт
not stated    366
down           24
не указано     19
up             12
Name: count, dtype: int64

In [350]:
df449_full_good.loc[df449_full_good['импорт'] == 'не указано', 'импорт'] = 'not stated'

In [351]:
df449_full_good['импорт'].value_counts()

импорт
not stated    385
down           24
up             12
Name: count, dtype: int64

In [352]:
# экспорт
df449_full_good['экспорт'].value_counts()

экспорт
not stated                               308
up                                        55
down                                      38
не указано                                18
up»,                                       1
up» (азотные удобрения, экспорт в ЕС)      1
Name: count, dtype: int64

In [353]:
df449_full_good.loc[df449_full_good['экспорт'] == 'не указано', 'экспорт'] = 'not stated'
df449_full_good.loc[df449_full_good['экспорт'] == 'up» (азотные удобрения, экспорт в ЕС)', 'экспорт'] = 'up'
df449_full_good.loc[df449_full_good['экспорт'] == 'up»,', 'экспорт'] = 'up'

In [354]:
df449_full_good['экспорт'].value_counts()

экспорт
not stated    326
up             57
down           38
Name: count, dtype: int64

In [355]:
# государственные расходы
df449_full_good['государственные расходы'].value_counts()

государственные расходы
not stated    395
не указано     19
up              7
Name: count, dtype: int64

In [356]:
df449_full_good.loc[df449_full_good['государственные расходы'] == 'не указано', 'государственные расходы'] = 'not stated'

In [357]:
df449_full_good['государственные расходы'].value_counts()

государственные расходы
not stated    414
up              7
Name: count, dtype: int64

In [ ]:
# государственный долг
df449_full_good['государственный долг'].value_counts()

государственный долг
not stated    387
не указано     19
up             14
down            1
Name: count, dtype: int64

In [359]:
df449_full_good.loc[df449_full_good['государственный долг'] == 'не указано', 'государственный долг'] = 'not stated'

In [360]:
df449_full_good['государственный долг'].value_counts()

государственный долг
not stated    406
up             14
down            1
Name: count, dtype: int64

In [361]:
# дефицит бюджета
df449_full_good['дефицит бюджета'].value_counts()

дефицит бюджета
not stated    378
up             19
не указано     19
down            5
Name: count, dtype: int64

In [362]:
df449_full_good.loc[df449_full_good['дефицит бюджета'] == 'не указано', 'дефицит бюджета'] = 'not stated'

In [363]:
df449_full_good['дефицит бюджета'].value_counts()

дефицит бюджета
not stated    397
up             19
down            5
Name: count, dtype: int64

In [364]:
## инфляция
df449_full_good['инфляция'].value_counts()

инфляция
not stated    345
up             47
не указано     18
down           11
Name: count, dtype: int64

In [365]:
df449_full_good.loc[df449_full_good['инфляция'] == 'не указано', 'инфляция'] = 'not stated'

In [366]:
df449_full_good['инфляция'].value_counts()

инфляция
not stated    363
up             47
down           11
Name: count, dtype: int64

In [367]:
df449_full_good.to_csv('df449_full_good.csv', index=False)

In [ ]:
#df449_full.to_csv('siksnmdc.csv', index=False)

## 3-АЯ ЧАСТЬ РАЗМЕТКИ(НА АККАУНТЕ КОНЧИЛИСЬ ТОКЕНЫ, ВЗЯЛИ НОВЫЙ) - c 449 до 1000

In [ ]:
AUTH_KEY = "=="

In [371]:
print("🚀 Начинаю разметку через GigaChat...")
dataset_449_1000 = list(data['chunk_text'])[449:1000]
results_3 = []

# verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
    for i, text in enumerate(dataset_449_1000, 1):
        print(f'Обработка документа {i + 449}...')
        label = label_data(text, giga)
        label['doc_id'] = data.iloc[i + 449, 0]
        label['chunk_id'] = data.iloc[i + 449, 1]
        label['original_text'] = text

        results_3.append(label)

🚀 Начинаю разметку через GigaChat...
Обработка документа 450...
Обработка документа 451...
Обработка документа 452...
Обработка документа 453...
Обработка документа 454...
Обработка документа 455...
Обработка документа 456...
Обработка документа 457...
Обработка документа 458...
Обработка документа 459...
Обработка документа 460...
Обработка документа 461...
Обработка документа 462...
Обработка документа 463...
Обработка документа 464...
Обработка документа 465...
Обработка документа 466...
Обработка документа 467...
Обработка документа 468...
Обработка документа 469...
Обработка документа 470...
Обработка документа 471...
Обработка документа 472...
Обработка документа 473...
Обработка документа 474...
Обработка документа 475...
Обработка документа 476...
Обработка документа 477...
Обработка документа 478...
Обработка документа 479...
Обработка документа 480...
Обработка документа 481...
Обработка документа 482...
Обработка документа 483...
Обработка документа 484...
Обработка документа 485...
Обработка документа 486...
Обработка документа 487...
Обработка документа 488...
Обработка документа 489...
Обработка документа 490...
Обработка документа 491...
Обработка документа 492...
Обработка документа 493...
Обработка документа 494...
Обработка документа 495...
Обработка документа 496...
Обработка документа 497...
Обработка документа 498...
Обработка документа 499...
Обработка документа 500...
Обработка документа 501...
Обработка документа 502...
Обработка документа 503...
Обработка документа 504...
Обработка документа 505...
Обработка документа 506...
Обработка документа 507...
Обработка документа 508...
Обработка документа 509...
Обработка документа 510...
Обработка документа 511...
Обработка документа 512...
Обработка документа 513...
Обработка документа 514...
Обработка документа 515...
Обработка документа 516...
Обработка документа 517...
Обработка документа 518...
Обработка документа 519...
Обработка документа 520...
Обработка документа 521...
Обработка документа 522...
Обработка документа 523...
Обработка документа 524...
Обработка документа 525...
Обработка документа 526...
Обработка документа 527...
Обработка документа 528...
Обработка документа 529...
Обработка документа 530...
Обработка документа 531...
Обработка документа 532...
Обработка документа 533...
Обработка документа 534...
Обработка документа 535...
Обработка документа 536...
Обработка документа 537...
Обработка документа 538...
Обработка документа 539...
Обработка документа 540...
Обработка документа 541...
Обработка документа 542...
Обработка документа 543...
Обработка документа 544...
Обработка документа 545...
Обработка документа 546...
Обработка документа 547...
Обработка документа 548...
Обработка документа 549...
Обработка документа 550...
Обработка документа 551...
Обработка документа 552...
Обработка документа 553...
Обработка документа 554...
Обработка документа 555...
Обработка документа 556...
Обработка документа 557...
Обработка документа 558...
Обработка документа 559...
Обработка документа 560...
Обработка документа 561...
Обработка документа 562...
Обработка документа 563...
Обработка документа 564...
Обработка документа 565...
Обработка документа 566...
Обработка документа 567...
Обработка документа 568...
Обработка документа 569...
Обработка документа 570...
Обработка документа 571...
Обработка документа 572...
Обработка документа 573...
Обработка документа 574...
Обработка документа 575...
Обработка документа 576...
Обработка документа 577...
Обработка документа 578...
Обработка документа 579...
Обработка документа 580...
Обработка документа 581...
Обработка документа 582...
Обработка документа 583...
Обработка документа 584...
Обработка документа 585...
Обработка документа 586...
Обработка документа 587...
Обработка документа 588...
Обработка документа 589...
Обработка документа 590...
Обработка документа 591...
Обработка документа 592...
Обработка документа 593...
Обработка документа 594...
Обработка документа 595...
Обработка документа 596...
Обработка документа 597...
Обработка документа 598...
Обработка документа 599...
Обработка документа 600...
Обработка документа 601...
Обработка документа 602...
Обработка документа 603...
Обработка документа 604...
Обработка документа 605...
Обработка документа 606...
Обработка документа 607...
Обработка документа 608...
Обработка документа 609...
Обработка документа 610...
Обработка документа 611...
Обработка документа 612...
Обработка документа 613...
Обработка документа 614...
Обработка документа 615...
Обработка документа 616...
Обработка документа 617...
Обработка документа 618...
Обработка документа 619...
Обработка документа 620...
Обработка документа 621...
Обработка документа 622...
Обработка документа 623...
Обработка документа 624...
Обработка документа 625...
Обработка документа 626...
Обработка документа 627...
Обработка документа 628...
Обработка документа 629...
Обработка документа 630...
Обработка документа 631...
Обработка документа 632...
Обработка документа 633...
Обработка документа 634...
Обработка документа 635...
Обработка документа 636...
Обработка документа 637...
Обработка документа 638...
Обработка документа 639...
Обработка документа 640...
Обработка документа 641...
Обработка документа 642...
Обработка документа 643...
Обработка документа 644...
Обработка документа 645...
Обработка документа 646...
Обработка документа 647...
Обработка документа 648...
Обработка документа 649...
Обработка документа 650...
Обработка документа 651...
Обработка документа 652...
Обработка документа 653...
Обработка документа 654...
Обработка документа 655...
Обработка документа 656...
Обработка документа 657...
Обработка документа 658...
Обработка документа 659...
Обработка документа 660...
Обработка документа 661...
Обработка документа 662...
Обработка документа 663...
Обработка документа 664...
Обработка документа 665...
Обработка документа 666...
Обработка документа 667...
Обработка документа 668...
Обработка документа 669...
Обработка документа 670...
Обработка документа 671...
Обработка документа 672...
Обработка документа 673...
Обработка документа 674...
Обработка документа 675...
Обработка документа 676...
Обработка документа 677...
Обработка документа 678...
Обработка документа 679...
Обработка документа 680...
Обработка документа 681...
Обработка документа 682...
Обработка документа 683...
Обработка документа 684...
Обработка документа 685...
Обработка документа 686...
Обработка документа 687...
Обработка документа 688...
Обработка документа 689...
Обработка документа 690...
Обработка документа 691...
Обработка документа 692...
Обработка документа 693...
Обработка документа 694...
Обработка документа 695...
Обработка документа 696...
Обработка документа 697...
Обработка документа 698...
Обработка документа 699...
Обработка документа 700...
Обработка документа 701...
Обработка документа 702...
Обработка документа 703...
Обработка документа 704...
Обработка документа 705...
Обработка документа 706...
Обработка документа 707...
Обработка документа 708...
Обработка документа 709...
Обработка документа 710...
Обработка документа 711...
Обработка документа 712...
Обработка документа 713...
Обработка документа 714...
Обработка документа 715...
Обработка документа 716...
Обработка документа 717...
Обработка документа 718...
Обработка документа 719...
Обработка документа 720...
Обработка документа 721...
Обработка документа 722...
Обработка документа 723...
Обработка документа 724...
Обработка документа 725...
Обработка документа 726...
Обработка документа 727...
Обработка документа 728...
Обработка документа 729...
Обработка документа 730...
Обработка документа 731...
Обработка документа 732...
Обработка документа 733...
Обработка документа 734...
Обработка документа 735...
Обработка документа 736...
Обработка документа 737...
Обработка документа 738...
Обработка документа 739...
Обработка документа 740...
Обработка документа 741...
Обработка документа 742...
Обработка документа 743...
Обработка документа 744...
Обработка документа 745...
Обработка документа 746...
Обработка документа 747...
Обработка документа 748...
Обработка документа 749...
Обработка документа 750...
Обработка документа 751...
Обработка документа 752...
Обработка документа 753...
Обработка документа 754...
Обработка документа 755...
Обработка документа 756...
Обработка документа 757...
Обработка документа 758...
Обработка документа 759...
Обработка документа 760...
Обработка документа 761...
Обработка документа 762...
Обработка документа 763...
Обработка документа 764...
Обработка документа 765...
Обработка документа 766...
Обработка документа 767...
Обработка документа 768...
Обработка документа 769...
Обработка документа 770...
Обработка документа 771...
Обработка документа 772...
Обработка документа 773...
Обработка документа 774...
Обработка документа 775...
Обработка документа 776...
Обработка документа 777...
Обработка документа 778...
Обработка документа 779...
Обработка документа 780...
Обработка документа 781...
Обработка документа 782...
Обработка документа 783...
Обработка документа 784...
Обработка документа 785...
Обработка документа 786...
Обработка документа 787...
Обработка документа 788...
Обработка документа 789...
Обработка документа 790...
Обработка документа 791...
Обработка документа 792...
Обработка документа 793...
Обработка документа 794...
Обработка документа 795...
Обработка документа 796...
Обработка документа 797...
Обработка документа 798...
Обработка документа 799...
Обработка документа 800...
Обработка документа 801...
Обработка документа 802...
Обработка документа 803...
Обработка документа 804...
Обработка документа 805...
Обработка документа 806...
Обработка документа 807...
Обработка документа 808...
Обработка документа 809...
Обработка документа 810...
Обработка документа 811...
Обработка документа 812...
Обработка документа 813...
Обработка документа 814...
Обработка документа 815...
Обработка документа 816...
Обработка документа 817...
Обработка документа 818...
Обработка документа 819...
Обработка документа 820...
Обработка документа 821...
Обработка документа 822...
Обработка документа 823...
Обработка документа 824...
Обработка документа 825...
Обработка документа 826...
Обработка документа 827...
Обработка документа 828...
Обработка документа 829...
Обработка документа 830...
Обработка документа 831...
Обработка документа 832...
Обработка документа 833...
Обработка документа 834...
Обработка документа 835...
Обработка документа 836...
Обработка документа 837...
Обработка документа 838...
Обработка документа 839...
Обработка документа 840...
Обработка документа 841...
Обработка документа 842...
Обработка документа 843...
Обработка документа 844...
Обработка документа 845...
Обработка документа 846...
Обработка документа 847...
Обработка документа 848...
Обработка документа 849...
Обработка документа 850...
Обработка документа 851...
Обработка документа 852...
Обработка документа 853...
Обработка документа 854...
Обработка документа 855...
Обработка документа 856...
Обработка документа 857...
Обработка документа 858...
Обработка документа 859...
Обработка документа 860...
Обработка документа 861...
Обработка документа 862...
Обработка документа 863...
Обработка документа 864...
Обработка документа 865...
Обработка документа 866...
Обработка документа 867...
Обработка документа 868...
Обработка документа 869...
Обработка документа 870...
Обработка документа 871...
Обработка документа 872...
Обработка документа 873...
Обработка документа 874...
Обработка документа 875...
Обработка документа 876...
Обработка документа 877...
Обработка документа 878...
Обработка документа 879...
Обработка документа 880...
Обработка документа 881...
Обработка документа 882...
Обработка документа 883...
Обработка документа 884...
Обработка документа 885...
Обработка документа 886...
Обработка документа 887...
Обработка документа 888...
Обработка документа 889...
Обработка документа 890...
Обработка документа 891...
Обработка документа 892...
Обработка документа 893...
Обработка документа 894...
Обработка документа 895...
Обработка документа 896...
Обработка документа 897...
Обработка документа 898...
Обработка документа 899...
Обработка документа 900...
Обработка документа 901...
Обработка документа 902...
Обработка документа 903...
Обработка документа 904...
Обработка документа 905...
Обработка документа 906...
Обработка документа 907...
Обработка документа 908...
Обработка документа 909...
Обработка документа 910...
Обработка документа 911...
Обработка документа 912...
Обработка документа 913...
Обработка документа 914...
Обработка документа 915...
Обработка документа 916...
Обработка документа 917...
Обработка документа 918...
Обработка документа 919...
Обработка документа 920...
Обработка документа 921...
Обработка документа 922...
Обработка документа 923...
Обработка документа 924...
Обработка документа 925...
Обработка документа 926...
Обработка документа 927...
Обработка документа 928...
Обработка документа 929...
Обработка документа 930...
Обработка документа 931...
Обработка документа 932...
Обработка документа 933...
Обработка документа 934...
Обработка документа 935...
Обработка документа 936...
Обработка документа 937...
Обработка документа 938...
Обработка документа 939...
Обработка документа 940...
Обработка документа 941...
Обработка документа 942...
Обработка документа 943...
Обработка документа 944...
Обработка документа 945...
Обработка документа 946...
Обработка документа 947...
Обработка документа 948...
Обработка документа 949...
Обработка документа 950...
Обработка документа 951...
Обработка документа 952...
Обработка документа 953...
Обработка документа 954...
Обработка документа 955...
Обработка документа 956...
Обработка документа 957...
Обработка документа 958...
Обработка документа 959...
Обработка документа 960...
Обработка документа 961...
Обработка документа 962...
Обработка документа 963...
Обработка документа 964...
Обработка документа 965...
Обработка документа 966...
Обработка документа 967...
Обработка документа 968...
Обработка документа 969...
Обработка документа 970...
Обработка документа 971...
Обработка документа 972...
Обработка документа 973...
Обработка документа 974...
Обработка документа 975...
Обработка документа 976...
Обработка документа 977...
Обработка документа 978...
Обработка документа 979...
Обработка документа 980...
Обработка документа 981...
Обработка документа 982...
Обработка документа 983...
Обработка документа 984...
Обработка документа 985...
Обработка документа 986...
Обработка документа 987...
Обработка документа 988...
Обработка документа 989...
Обработка документа 990...
Обработка документа 991...
Обработка документа 992...
Обработка документа 993...
Обработка документа 994...
Обработка документа 995...
Обработка документа 996...
Обработка документа 997...
Обработка документа 998...
Обработка документа 999...
Обработка документа 1000...

In [448]:
df1000

,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,потребление,численность рабочей силы,сбережения,...,доходы населения,валютный курс,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета,doc_id,chunk_id,original_text
0,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,...,не указано,не указано,не указано,не указано,не указано,не указано,не указано,326,3,Благодаря текущему оптимизму на американском р...
1,up,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,327,0,С начала года капитализация Microsoft выросла ...
2,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,...,не указано,не указано,не указано,не указано,не указано,не указано,не указано,328,0,"""️️️ Шокирующие прогнозы на 2024 год от Фёдора..."
3,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,330,0,""" Как закрылась основная торговая сессия на ро..."
4,up,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,330,2,""" Регуляторы разных стран пытаются остановить ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,not stated,down,not stated,not stated,down,down,down,not stated,not stated,not stated,...,not stated,not stated,down,not stated,not stated,not stated,not stated,759,0,"""Великобритания ввела новые санкции. Как реаги..."
547,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,up,not stated,up,760,0,"""Закрываем идею по Транснефти Мы закрываем на..."
548,up,not stated,not stated,down,not stated,not stated,not stated,not stated,up,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,760,1,"""Рынки снижаются, но Bank of America прогнозир..."
549,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,up,not stated,...,up,not stated,not stated,not stated,not stated,not stated,not stated,760,2,"По данным Refinitiv, экономисты прогнозируют, ..."
550,down,not stated,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,761,0,В Goldman Sachs обеспокоены приверженностью ки...

In [449]:
df1000 = pd.DataFrame(results_3)
df1000 = df1000.drop(['category', 'details', 'saving'], axis=1)
df_1000_good = df1000.dropna()

In [450]:
# процентная ставка
df_1000_good['процентная ставка'].value_counts()

процентная ставка
not stated    353
up             97
down           42
не указано     23
Name: count, dtype: int64

In [451]:
df_1000_good.loc[df_1000_good['процентная ставка'] == 'не указано', 'процентная ставка'] = 'not stated'

In [452]:
df_1000_good['процентная ставка'].value_counts()

процентная ставка
not stated    376
up             97
down           42
Name: count, dtype: int64

In [453]:
## ВВП
df_1000_good['ВВП'].value_counts()

ВВП
not stated    424
down           41
не указано     27
up             23
Name: count, dtype: int64

In [454]:
df_1000_good.loc[df_1000_good['ВВП'] == 'не указано', 'ВВП'] = 'not stated'

In [455]:
df_1000_good['ВВП'].value_counts()

ВВП
not stated    451
down           41
up             23
Name: count, dtype: int64

In [456]:
## безработица
df_1000_good['безработица'].value_counts()

безработица
not stated    463
не указано     28
up             13
down           11
Name: count, dtype: int64

In [457]:
df_1000_good.loc[df_1000_good['безработица'] == 'не указано', 'безработица'] = 'not stated'

In [458]:
df_1000_good['безработица'].value_counts()

безработица
not stated    491
up             13
down           11
Name: count, dtype: int64

In [459]:
## капитал
df_1000_good['капитал'].value_counts()

капитал
not stated                        407
up                                 53
down                               29
не указано                         24
up», (рост капитальных затрат)      1
not expanded                        1
Name: count, dtype: int64

In [460]:
df_1000_good.loc[df_1000_good['капитал'] == 'не указано', 'капитал'] = 'not stated'

df_1000_good.loc[df_1000_good['капитал'].apply(lambda x: x.split()[-1]) == 'expanded', 'капитал'] = 'not stated'
df_1000_good.loc[df_1000_good['капитал'] == 'up», (рост капитальных затрат)', 'капитал'] = 'up'

In [461]:
df_1000_good['капитал'].value_counts()

капитал
not stated    432
up             54
down           29
Name: count, dtype: int64

In [462]:
# инвестиции
df_1000_good['инвестиции'].value_counts()

инвестиции
not stated    418
down           36
up             34
не указано     27
Name: count, dtype: int64

In [463]:
df_1000_good.loc[df_1000_good['инвестиции'] == 'не указано', 'инвестиции'] = 'not stated'

In [464]:
df_1000_good['инвестиции'].value_counts()

инвестиции
not stated    445
down           36
up             34
Name: count, dtype: int64

In [ ]:
# производство
df_1000_good['производство'].value_counts()

производство
not stated    391
down           60
up             38
не указано     26
Name: count, dtype: int64

In [466]:
df_1000_good.loc[df_1000_good['производство'] == 'не указано', 'производство'] = 'not stated'

In [467]:
df_1000_good['производство'].value_counts()

производство
not stated    417
down           60
up             38
Name: count, dtype: int64

In [468]:
# потребление
df_1000_good['потребление'].value_counts()

потребление
not stated    451
не указано     28
down           20
up             16
Name: count, dtype: int64

In [469]:
df_1000_good.loc[df_1000_good['потребление'] == 'не указано', 'потребление'] = 'not stated'

In [470]:
df_1000_good['потребление'].value_counts()

потребление
not stated    479
down           20
up             16
Name: count, dtype: int64

In [471]:
# численность рабочей силы
df_1000_good['численность рабочей силы'].value_counts()

численность рабочей силы
not stated    469
не указано     28
down           11
up              7
Name: count, dtype: int64

In [ ]:
df_1000_good.loc[df_1000_good['численность рабочей силы'] == 'не указано', 'численность рабочей силы'] = 'not stated'

In [473]:
df_1000_good['численность рабочей силы'].value_counts()

численность рабочей силы
not stated    497
down           11
up              7
Name: count, dtype: int64

In [474]:
# сбережения
df_1000_good['сбережения'].value_counts()

сбережения
not stated    479
не указано     28
up              6
down            2
Name: count, dtype: int64

In [475]:
df_1000_good.loc[df_1000_good['сбережения'] == 'не указано', 'сбережения'] = 'not stated'

In [476]:
df_1000_good['сбережения'].value_counts()

сбережения
not stated    507
up              6
down            2
Name: count, dtype: int64

In [477]:
# заработные платы
df_1000_good['заработные платы'].value_counts()

заработные платы
not stated    456
не указано     28
down           18
up             13
Name: count, dtype: int64

In [512]:
df_1000_good.loc[df_1000_good['заработные платы'] == 'не указано', 'заработные платы'] = 'not stated'

In [479]:
df_1000_good['заработные платы'].value_counts()

заработные платы
not stated    484
down           18
up             13
Name: count, dtype: int64

In [480]:
# доходы населения
df_1000_good['доходы населения'].value_counts()

доходы населения
not stated    439
не указано     28
up             24
down           24
Name: count, dtype: int64

In [481]:
df_1000_good.loc[df_1000_good['доходы населения'] == 'не указано', 'доходы населения'] = 'not stated'
df_1000_good.loc[df_1000_good['доходы населения'].apply(lambda x: x.split()[0]) == 'не', 'доходы населения'] = 'up'

In [482]:
df_1000_good['доходы населения'].value_counts()

доходы населения
not stated    467
up             24
down           24
Name: count, dtype: int64

In [483]:
# валютный курс
df_1000_good['валютный курс'].value_counts()

валютный курс
not stated                               397
up                                        54
down                                      35
не указано                                23
up-down                                    3
up/down                                    1
не указано (зависит от динамики)           1
up (краткосрочно), down (долгосрочно)      1
Name: count, dtype: int64

In [485]:
df_1000_good.loc[df_1000_good['валютный курс'] == 'не указано', 'валютный курс'] = 'not stated'
df_1000_good.loc[df_1000_good['валютный курс'] == 'не указано (зависит от динамики)', 'валютный курс'] = 'not stated'

df_1000_good.loc[df_1000_good['валютный курс'] == 'up/down', 'валютный курс'] = 'up'
df_1000_good.loc[df_1000_good['валютный курс'] == 'up-down', 'валютный курс'] = 'up'
df_1000_good.loc[df_1000_good['валютный курс'] == 'up (краткосрочно), down (долгосрочно)', 'валютный курс'] = 'up'

In [486]:
df_1000_good['валютный курс'].value_counts()

валютный курс
not stated    421
up             59
down           35
Name: count, dtype: int64

In [487]:
# импорт
df_1000_good['импорт'].value_counts()

импорт
not stated    453
не указано     28
down           24
up             10
Name: count, dtype: int64

In [488]:
df_1000_good.loc[df_1000_good['импорт'] == 'не указано', 'импорт'] = 'not stated'

In [489]:
df_1000_good['импорт'].value_counts()

импорт
not stated    481
down           24
up             10
Name: count, dtype: int64

In [490]:
# экспорт
df_1000_good['экспорт'].value_counts()

экспорт
not stated    401
up             56
down           31
не указано     27
Name: count, dtype: int64

In [491]:
df_1000_good.loc[df_1000_good['экспорт'] == 'не указано', 'экспорт'] = 'not stated'

In [ ]:
df_1000_good['экспорт'].value_counts()

экспорт
not stated    428
up             56
down           31
Name: count, dtype: int64

In [493]:
# государственные расходы
df_1000_good['государственные расходы'].value_counts()

государственные расходы
not stated    475
не указано     27
up             11
down            1
neutral         1
Name: count, dtype: int64

In [494]:
df_1000_good.loc[df_1000_good['государственные расходы'] == 'не указано', 'государственные расходы'] = 'not stated'

df_1000_good.loc[df_1000_good['государственные расходы'] == 'neutral', 'государственные расходы'] = 'not stated'

In [495]:
df_1000_good['государственные расходы'].value_counts()

государственные расходы
not stated    503
up             11
down            1
Name: count, dtype: int64

In [496]:
# государственный долг
df_1000_good['государственный долг'].value_counts()

государственный долг
not stated    471
не указано     27
up             15
down            1
неизменен       1
Name: count, dtype: int64

In [497]:
df_1000_good.loc[df_1000_good['государственный долг'] == 'не указано', 'государственный долг'] = 'not stated'
df_1000_good.loc[df_1000_good['государственный долг'] == 'неизменен', 'государственный долг'] = 'not stated'

In [498]:
df_1000_good['государственный долг'].value_counts()

государственный долг
not stated    499
up             15
down            1
Name: count, dtype: int64

In [499]:
# дефицит бюджета
df_1000_good['дефицит бюджета'].value_counts()

дефицит бюджета
not stated    467
не указано     27
up             19
down            1
neutral         1
Name: count, dtype: int64

In [500]:
df_1000_good.loc[df_1000_good['дефицит бюджета'] == 'не указано', 'дефицит бюджета'] = 'not stated'
df_1000_good.loc[df_1000_good['дефицит бюджета'] == 'neutral', 'дефицит бюджета'] = 'not stated'

In [501]:
df_1000_good['дефицит бюджета'].value_counts()

дефицит бюджета
not stated    495
up             19
down            1
Name: count, dtype: int64

In [502]:
## инфляция
df_1000_good['инфляция'].value_counts()

инфляция
not stated                  415
up                           50
не указано                   27
down                         22
up (по словам чиновника)      1
Name: count, dtype: int64

In [503]:
df_1000_good.loc[df_1000_good['инфляция'] == 'не указано', 'инфляция'] = 'not stated'
df_1000_good.loc[df_1000_good['инфляция'] == 'up (по словам чиновника)', 'инфляция'] = 'up'

In [504]:
df_1000_good['инфляция'].value_counts()

инфляция
not stated    442
up             51
down           22
Name: count, dtype: int64

In [508]:
df_1000_all = pd.concat([df449_full_good, df_1000_good], axis=0)
df_1000_all

,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,потребление,численность рабочей силы,сбережения,...,доходы населения,валютный курс,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета,doc_id,chunk_id,original_text
0,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1,0,"""Индекс Мосбиржи -3%. Это самое большое дневно..."
1,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,2,0,"""​​Циан взлетел на апелляции Крупнейший в Росс..."
2,not stated,down,up,not stated,not stated,not stated,down,not stated,not stated,not stated,...,down,not stated,not stated,down,not stated,not stated,up,2,1,"""С 5 февраля ЕС вводит эмбарго на российские п..."
3,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,up,3,0,Госбюджет РФ рискует недополучить еще больше н...
4,not stated,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,4,0,"""Новый отчёт Сбера (SBER): чистая прибыль за 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,not stated,down,not stated,not stated,down,down,down,not stated,not stated,not stated,...,not stated,not stated,down,not stated,not stated,not stated,not stated,759,0,"""Великобритания ввела новые санкции. Как реаги..."
547,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,up,not stated,up,760,0,"""Закрываем идею по Транснефти Мы закрываем на..."
548,up,not stated,not stated,down,not stated,not stated,not stated,not stated,up,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,760,1,"""Рынки снижаются, но Bank of America прогнозир..."
549,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,up,not stated,...,up,not stated,not stated,not stated,not stated,not stated,not stated,760,2,"По данным Refinitiv, экономисты прогнозируют, ..."
550,down,not stated,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,761,0,В Goldman Sachs обеспокоены приверженностью ки...

In [509]:
df_1000_all.to_csv('df_1000_all_good.csv', index=False)

## СПОРТСМЕНЫ НА МЕСТЕ? РАЗМЕЧАЕМ С 1000 ДО 2000

In [511]:
print("🚀 Начинаю разметку через GigaChat...")
dataset_1000_end = list(data['chunk_text'])[1000:]
results_4 = []

# verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
    for i, text in enumerate(dataset_1000_end, 1):
        print(f'Обработка документа {i + 1000}...')
        label = label_data(text, giga)
        label['doc_id'] = data.iloc[i + 1000, 0]
        label['chunk_id'] = data.iloc[i + 1000, 1]
        label['original_text'] = text

        results_4.append(label)

🚀 Начинаю разметку через GigaChat...
Обработка документа 1001...
Обработка документа 1002...
Обработка документа 1003...
Обработка документа 1004...
Обработка документа 1005...
Обработка документа 1006...
Обработка документа 1007...
Обработка документа 1008...
Обработка документа 1009...
Обработка документа 1010...
Обработка документа 1011...
Обработка документа 1012...
Обработка документа 1013...
Обработка документа 1014...
Обработка документа 1015...
Обработка документа 1016...
Обработка документа 1017...
Обработка документа 1018...
Обработка документа 1019...
Обработка документа 1020...
Обработка документа 1021...
Обработка документа 1022...
Обработка документа 1023...
Обработка документа 1024...
Обработка документа 1025...
Обработка документа 1026...
Обработка документа 1027...
Обработка документа 1028...
Обработка документа 1029...
Обработка документа 1030...
Обработка документа 1031...
Обработка документа 1032...
Обработка документа 1033...
Обработка документа 1034...
Обработка документа 1035...
Обработка документа 1036...
Обработка документа 1037...
Обработка документа 1038...
Обработка документа 1039...
Обработка документа 1040...
Обработка документа 1041...
Обработка документа 1042...
Обработка документа 1043...
Обработка документа 1044...
Обработка документа 1045...
Обработка документа 1046...
Обработка документа 1047...
Обработка документа 1048...
Обработка документа 1049...
Обработка документа 1050...
Обработка документа 1051...
Обработка документа 1052...
Обработка документа 1053...
Обработка документа 1054...
Обработка документа 1055...
Обработка документа 1056...
Обработка документа 1057...
Обработка документа 1058...
Обработка документа 1059...
Обработка документа 1060...
Обработка документа 1061...
Обработка документа 1062...
Обработка документа 1063...
Обработка документа 1064...
Обработка документа 1065...
Обработка документа 1066...
Обработка документа 1067...
Обработка документа 1068...
Обработка документа 1069...
Обработка документа 1070...
Обработка документа 1071...
Обработка документа 1072...
Обработка документа 1073...
Обработка документа 1074...
Обработка документа 1075...
Обработка документа 1076...
Обработка документа 1077...
Обработка документа 1078...
Обработка документа 1079...
Обработка документа 1080...
Обработка документа 1081...
Обработка документа 1082...
Обработка документа 1083...
Обработка документа 1084...
Обработка документа 1085...
Обработка документа 1086...
Обработка документа 1087...
Обработка документа 1088...
Обработка документа 1089...
Обработка документа 1090...
Обработка документа 1091...
Обработка документа 1092...
Обработка документа 1093...
Обработка документа 1094...
Обработка документа 1095...
Обработка документа 1096...
Обработка документа 1097...
Обработка документа 1098...
Обработка документа 1099...
Обработка документа 1100...
Обработка документа 1101...
Обработка документа 1102...
Обработка документа 1103...
Обработка документа 1104...
Обработка документа 1105...
Обработка документа 1106...
Обработка документа 1107...
Обработка документа 1108...
Обработка документа 1109...
Обработка документа 1110...
Обработка документа 1111...
Обработка документа 1112...
Обработка документа 1113...
Обработка документа 1114...
Обработка документа 1115...
Обработка документа 1116...
Обработка документа 1117...
Обработка документа 1118...
Обработка документа 1119...
Обработка документа 1120...
Обработка документа 1121...
Обработка документа 1122...
Обработка документа 1123...
Обработка документа 1124...
Обработка документа 1125...
Обработка документа 1126...
Обработка документа 1127...
Обработка документа 1128...
Обработка документа 1129...
Обработка документа 1130...
Обработка документа 1131...
Обработка документа 1132...
Обработка документа 1133...
Обработка документа 1134...
Обработка документа 1135...
Обработка документа 1136...
Обработка документа 1137...
Обработка документа 1138...
Обработка документа 1139...
Обработка документа 1140...
Обработка документа 1141...
Обработка документа 1142...
Обработка документа 1143...
Обработка документа 1144...
Обработка документа 1145...
Обработка документа 1146...
Обработка документа 1147...
Обработка документа 1148...
Обработка документа 1149...
Обработка документа 1150...
Обработка документа 1151...
Обработка документа 1152...
Обработка документа 1153...
Обработка документа 1154...
Обработка документа 1155...
Обработка документа 1156...
Обработка документа 1157...
Обработка документа 1158...
Обработка документа 1159...
Обработка документа 1160...
Обработка документа 1161...
Обработка документа 1162...
Обработка документа 1163...
Обработка документа 1164...
Обработка документа 1165...
Обработка документа 1166...
Обработка документа 1167...
Обработка документа 1168...
Обработка документа 1169...
Обработка документа 1170...
Обработка документа 1171...
Обработка документа 1172...
Обработка документа 1173...
Обработка документа 1174...
Обработка документа 1175...
Обработка документа 1176...
Обработка документа 1177...
Обработка документа 1178...
Обработка документа 1179...
Обработка документа 1180...
Обработка документа 1181...
Обработка документа 1182...
Обработка документа 1183...
Обработка документа 1184...
Обработка документа 1185...
Обработка документа 1186...
Обработка документа 1187...
Обработка документа 1188...
Обработка документа 1189...
Обработка документа 1190...
Обработка документа 1191...
Обработка документа 1192...
Обработка документа 1193...
Обработка документа 1194...
Обработка документа 1195...
Обработка документа 1196...
Обработка документа 1197...
Обработка документа 1198...
Обработка документа 1199...
Обработка документа 1200...
Обработка документа 1201...
Обработка документа 1202...
Обработка документа 1203...
Обработка документа 1204...
Обработка документа 1205...
Обработка документа 1206...
Обработка документа 1207...
Обработка документа 1208...
Обработка документа 1209...
Обработка документа 1210...
Обработка документа 1211...
Обработка документа 1212...
Обработка документа 1213...
Обработка документа 1214...
Обработка документа 1215...
Обработка документа 1216...
Обработка документа 1217...
Обработка документа 1218...
Обработка документа 1219...
Обработка документа 1220...
Обработка документа 1221...
Обработка документа 1222...
Обработка документа 1223...
Обработка документа 1224...
Обработка документа 1225...
Обработка документа 1226...
Обработка документа 1227...
Обработка документа 1228...
Обработка документа 1229...
Обработка документа 1230...
Обработка документа 1231...
Обработка документа 1232...
Обработка документа 1233...
Обработка документа 1234...
Обработка документа 1235...
Обработка документа 1236...
Обработка документа 1237...
Обработка документа 1238...
Обработка документа 1239...
Обработка документа 1240...
Обработка документа 1241...
Обработка документа 1242...
Обработка документа 1243...
Обработка документа 1244...
Обработка документа 1245...
Обработка документа 1246...
Обработка документа 1247...
Обработка документа 1248...
Обработка документа 1249...
Обработка документа 1250...
Обработка документа 1251...
Обработка документа 1252...
Обработка документа 1253...
Обработка документа 1254...
Обработка документа 1255...
Обработка документа 1256...
Обработка документа 1257...
Обработка документа 1258...
Обработка документа 1259...
Обработка документа 1260...
Обработка документа 1261...
Обработка документа 1262...
Обработка документа 1263...
Обработка документа 1264...
Обработка документа 1265...
Обработка документа 1266...
Обработка документа 1267...
Обработка документа 1268...
Обработка документа 1269...
Обработка документа 1270...
Обработка документа 1271...
Обработка документа 1272...
Обработка документа 1273...
Обработка документа 1274...
Обработка документа 1275...
Обработка документа 1276...
Обработка документа 1277...
Обработка документа 1278...
Обработка документа 1279...
Обработка документа 1280...
Обработка документа 1281...
Обработка документа 1282...
Обработка документа 1283...
Обработка документа 1284...
Обработка документа 1285...
Обработка документа 1286...
Обработка документа 1287...
Обработка документа 1288...
Обработка документа 1289...
Обработка документа 1290...
Обработка документа 1291...
Обработка документа 1292...
Обработка документа 1293...
Обработка документа 1294...
Обработка документа 1295...
Обработка документа 1296...
Обработка документа 1297...
Обработка документа 1298...
Обработка документа 1299...
Обработка документа 1300...
Обработка документа 1301...
Обработка документа 1302...
Обработка документа 1303...
Обработка документа 1304...
Обработка документа 1305...
Обработка документа 1306...
Обработка документа 1307...
Обработка документа 1308...
Обработка документа 1309...
Обработка документа 1310...
Обработка документа 1311...
Обработка документа 1312...
Обработка документа 1313...
Обработка документа 1314...
Обработка документа 1315...
Обработка документа 1316...
Обработка документа 1317...
Обработка документа 1318...
Обработка документа 1319...
Обработка документа 1320...
Обработка документа 1321...
Обработка документа 1322...
Обработка документа 1323...
Обработка документа 1324...
Обработка документа 1325...
Обработка документа 1326...
Обработка документа 1327...
Обработка документа 1328...
Обработка документа 1329...
Обработка документа 1330...
Обработка документа 1331...
Обработка документа 1332...
Обработка документа 1333...
Обработка документа 1334...
Обработка документа 1335...
Обработка документа 1336...
Обработка документа 1337...
Обработка документа 1338...
Обработка документа 1339...
Обработка документа 1340...
Обработка документа 1341...
Обработка документа 1342...
Обработка документа 1343...
Обработка документа 1344...
Обработка документа 1345...
Обработка документа 1346...
Обработка документа 1347...
Обработка документа 1348...
Обработка документа 1349...
Обработка документа 1350...
Обработка документа 1351...
Обработка документа 1352...
Обработка документа 1353...
Обработка документа 1354...
Обработка документа 1355...
Обработка документа 1356...
Обработка документа 1357...
Обработка документа 1358...
Обработка документа 1359...
Обработка документа 1360...
Обработка документа 1361...
Обработка документа 1362...
Обработка документа 1363...
Обработка документа 1364...
Обработка документа 1365...
Обработка документа 1366...
Обработка документа 1367...
Обработка документа 1368...
Обработка документа 1369...
Обработка документа 1370...
Обработка документа 1371...
Обработка документа 1372...
Обработка документа 1373...
Обработка документа 1374...
Обработка документа 1375...
Обработка документа 1376...
Обработка документа 1377...
Обработка документа 1378...
Обработка документа 1379...
Обработка документа 1380...
Обработка документа 1381...
Обработка документа 1382...
Обработка документа 1383...
Обработка документа 1384...
Обработка документа 1385...
Обработка документа 1386...
Обработка документа 1387...
Обработка документа 1388...
Обработка документа 1389...
Обработка документа 1390...
Обработка документа 1391...
Обработка документа 1392...
Обработка документа 1393...
Обработка документа 1394...
Обработка документа 1395...
Обработка документа 1396...
Обработка документа 1397...
Обработка документа 1398...
Обработка документа 1399...
Обработка документа 1400...
Обработка документа 1401...
Обработка документа 1402...
Обработка документа 1403...
Обработка документа 1404...
Обработка документа 1405...
Обработка документа 1406...
Обработка документа 1407...
Обработка документа 1408...
Обработка документа 1409...
Обработка документа 1410...
Обработка документа 1411...
Обработка документа 1412...
Обработка документа 1413...
Обработка документа 1414...
Обработка документа 1415...
Обработка документа 1416...
Обработка документа 1417...
Обработка документа 1418...
Обработка документа 1419...
Обработка документа 1420...
Обработка документа 1421...
Обработка документа 1422...
Обработка документа 1423...
Обработка документа 1424...
Обработка документа 1425...
Обработка документа 1426...
Обработка документа 1427...
Обработка документа 1428...
Обработка документа 1429...
Обработка документа 1430...
Обработка документа 1431...
Обработка документа 1432...
Обработка документа 1433...
Обработка документа 1434...
Обработка документа 1435...
Обработка документа 1436...
Обработка документа 1437...
Обработка документа 1438...
Обработка документа 1439...
Обработка документа 1440...
Обработка документа 1441...
Обработка документа 1442...
Обработка документа 1443...
Обработка документа 1444...
Обработка документа 1445...
Обработка документа 1446...
Обработка документа 1447...
Обработка документа 1448...
Обработка документа 1449...
Обработка документа 1450...
Обработка документа 1451...
Обработка документа 1452...
Обработка документа 1453...
Обработка документа 1454...
Обработка документа 1455...
Обработка документа 1456...
Обработка документа 1457...
Обработка документа 1458...
Обработка документа 1459...
Обработка документа 1460...
Обработка документа 1461...
Обработка документа 1462...
Обработка документа 1463...
Обработка документа 1464...
Обработка документа 1465...
Обработка документа 1466...
Обработка документа 1467...
Обработка документа 1468...
Обработка документа 1469...
Обработка документа 1470...
Обработка документа 1471...
Обработка документа 1472...
Обработка документа 1473...
Обработка документа 1474...
Обработка документа 1475...
Обработка документа 1476...
Обработка документа 1477...
Обработка документа 1478...
Обработка документа 1479...
Обработка документа 1480...
Обработка документа 1481...
Обработка документа 1482...
Обработка документа 1483...
Обработка документа 1484...
Обработка документа 1485...
Обработка документа 1486...
Обработка документа 1487...
Обработка документа 1488...
Обработка документа 1489...
Обработка документа 1490...
Обработка документа 1491...
Обработка документа 1492...
Обработка документа 1493...
Обработка документа 1494...
Обработка документа 1495...
Обработка документа 1496...
Обработка документа 1497...
Обработка документа 1498...
Обработка документа 1499...
Обработка документа 1500...
Обработка документа 1501...
Обработка документа 1502...
Обработка документа 1503...
Обработка документа 1504...
Обработка документа 1505...
Обработка документа 1506...
Обработка документа 1507...
Обработка документа 1508...
Обработка документа 1509...
Обработка документа 1510...
Обработка документа 1511...
Обработка документа 1512...
Обработка документа 1513...
Обработка документа 1514...
Обработка документа 1515...
Обработка документа 1516...
Обработка документа 1517...
Обработка документа 1518...
Обработка документа 1519...
Обработка документа 1520...
Обработка документа 1521...
Обработка документа 1522...
Обработка документа 1523...
Обработка документа 1524...
Обработка документа 1525...
Обработка документа 1526...
Обработка документа 1527...
Обработка документа 1528...
Обработка документа 1529...
Обработка документа 1530...
Обработка документа 1531...
Обработка документа 1532...
Обработка документа 1533...
Обработка документа 1534...
Обработка документа 1535...
Обработка документа 1536...
Обработка документа 1537...
Обработка документа 1538...
Обработка документа 1539...
Обработка документа 1540...
Обработка документа 1541...
Обработка документа 1542...
Обработка документа 1543...
Обработка документа 1544...
Обработка документа 1545...
Обработка документа 1546...
Обработка документа 1547...
Обработка документа 1548...
Обработка документа 1549...
Обработка документа 1550...
Обработка документа 1551...
Обработка документа 1552...
Обработка документа 1553...
Обработка документа 1554...
Обработка документа 1555...
Обработка документа 1556...
Обработка документа 1557...
Обработка документа 1558...
Обработка документа 1559...
Обработка документа 1560...
Обработка документа 1561...
Обработка документа 1562...
Обработка документа 1563...
Обработка документа 1564...
Обработка документа 1565...
Обработка документа 1566...
Обработка документа 1567...
Обработка документа 1568...
Обработка документа 1569...
Обработка документа 1570...
Обработка документа 1571...
Обработка документа 1572...
Обработка документа 1573...
Обработка документа 1574...
Обработка документа 1575...
Обработка документа 1576...
Обработка документа 1577...
Обработка документа 1578...
Обработка документа 1579...
Обработка документа 1580...
Обработка документа 1581...
Обработка документа 1582...
Обработка документа 1583...
Обработка документа 1584...
Обработка документа 1585...
Обработка документа 1586...
Обработка документа 1587...
Обработка документа 1588...
Обработка документа 1589...
Обработка документа 1590...
Обработка документа 1591...
Обработка документа 1592...
Обработка документа 1593...
Обработка документа 1594...
Обработка документа 1595...
Обработка документа 1596...
Обработка документа 1597...
Обработка документа 1598...
Обработка документа 1599...
Обработка документа 1600...
Обработка документа 1601...
Обработка документа 1602...
Обработка документа 1603...
Обработка документа 1604...
Обработка документа 1605...
Обработка документа 1606...
Обработка документа 1607...
Обработка документа 1608...
Обработка документа 1609...
Обработка документа 1610...
Обработка документа 1611...
Обработка документа 1612...
Обработка документа 1613...
Обработка документа 1614...
Обработка документа 1615...
Обработка документа 1616...
Обработка документа 1617...
Обработка документа 1618...
Обработка документа 1619...
Обработка документа 1620...
Обработка документа 1621...
Обработка документа 1622...
Обработка документа 1623...
Обработка документа 1624...
Обработка документа 1625...
Обработка документа 1626...
Обработка документа 1627...
Обработка документа 1628...
Обработка документа 1629...
Обработка документа 1630...
Обработка документа 1631...
Обработка документа 1632...
Обработка документа 1633...
Обработка документа 1634...
Обработка документа 1635...
Обработка документа 1636...
Обработка документа 1637...
Обработка документа 1638...
Обработка документа 1639...
Обработка документа 1640...
Обработка документа 1641...
Обработка документа 1642...
Обработка документа 1643...
Обработка документа 1644...
Обработка документа 1645...
Обработка документа 1646...
Обработка документа 1647...
Обработка документа 1648...
Обработка документа 1649...
Обработка документа 1650...
Обработка документа 1651...
Обработка документа 1652...
Обработка документа 1653...
Обработка документа 1654...
Обработка документа 1655...
Обработка документа 1656...
Обработка документа 1657...
Обработка документа 1658...
Обработка документа 1659...
Обработка документа 1660...
Обработка документа 1661...
Обработка документа 1662...
Обработка документа 1663...
Обработка документа 1664...
Обработка документа 1665...
Обработка документа 1666...
Обработка документа 1667...
Обработка документа 1668...
Обработка документа 1669...
Обработка документа 1670...
Обработка документа 1671...
Обработка документа 1672...
Обработка документа 1673...
Обработка документа 1674...
Обработка документа 1675...
Обработка документа 1676...
Обработка документа 1677...
Обработка документа 1678...
Обработка документа 1679...
Обработка документа 1680...
Обработка документа 1681...
Обработка документа 1682...
Обработка документа 1683...
Обработка документа 1684...
Обработка документа 1685...
Обработка документа 1686...
Обработка документа 1687...
Обработка документа 1688...
Обработка документа 1689...
Обработка документа 1690...
Обработка документа 1691...
Обработка документа 1692...
Обработка документа 1693...
Обработка документа 1694...
Обработка документа 1695...
Обработка документа 1696...
Обработка документа 1697...
Обработка документа 1698...
Обработка документа 1699...
Обработка документа 1700...
Обработка документа 1701...
Обработка документа 1702...
Обработка документа 1703...
Обработка документа 1704...
Обработка документа 1705...
Обработка документа 1706...
Обработка документа 1707...
Обработка документа 1708...
Обработка документа 1709...
Обработка документа 1710...
Обработка документа 1711...
Обработка документа 1712...

IndexError: index 1954 is out of bounds for axis 0 with size 1954

In [514]:
df2000

,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,потребление,численность рабочей силы,сбережения,...,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета,doc_id,chunk_id,original_text,category,details
0,not stated,not stated,up,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,762,0,"""Среднегодовая доходность активов в России за ...",NaN,NaN
1,up,not stated,down,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,762,1,"""Пауэлл не смог напугать инвесторов, а нефть д...",NaN,NaN
2,up,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,762,2,"Между тем, участники рынка с 20%-й вероятность...",NaN,NaN
3,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,762,3,Эти стимулирующие меры направлены на оживление...,NaN,NaN
4,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,не указано,...,не указано,не указано,не указано,не указано,не указано,762,4,За тот же период выручка компании составила 12...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,1491,0,В начале октября валютный курс тестирует сопро...,NaN,NaN
949,not stated,down,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,...,up,down,not stated,not stated,not stated,1491,4,"""Финансовый конгресс Банка России: что важного...",NaN,NaN
950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1492,0,Этот хаб можно расположить в одной из стран Пе...,Ошибка,Expecting value: line 1 column 1 (char 0)
951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1495,2,"""За последние 2 недели рубль ослаб почти на 8%...",NaN,NaN
952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1499,4,• Нефть дорожает По итогам вчерашних торгов ф...,Ошибка,Invalid control character at: line 6 column 19...

In [602]:
df2000 = pd.DataFrame(results_4)
df2000 = df2000.drop(['category', 'details'], axis=1)
df_2000_good = df2000.dropna()

In [603]:
df_2000_good.to_csv('df_2000_good.csv', index=False)

In [604]:
# процентная ставка
df_2000_good['процентная ставка'].value_counts()

процентная ставка
not stated                    573
up                            192
не указано                     53
down                           51
up or down (неопределенно)      1
Name: count, dtype: int64

In [605]:
df_2000_good.loc[df_2000_good['процентная ставка'] == 'не указано', 'процентная ставка'] = 'not stated'
df_2000_good.loc[df_2000_good['процентная ставка'] == 'up or down (неопределенно)', 'процентная ставка'] = 'not stated'

In [606]:
df_2000_good['процентная ставка'].value_counts()

процентная ставка
not stated    627
up            192
down           51
Name: count, dtype: int64

In [607]:
## ВВП
df_2000_good['ВВП'].value_counts()

ВВП
not stated    678
down           99
не указано     50
up             43
Name: count, dtype: int64

In [608]:
df_2000_good.loc[df_2000_good['ВВП'] == 'не указано', 'ВВП'] = 'not stated'

In [609]:
df_2000_good['ВВП'].value_counts()

ВВП
not stated    728
down           99
up             43
Name: count, dtype: int64

In [611]:
## безработица
df_2000_good['безработица'].value_counts()

безработица
not stated    801
не указано     54
up             10
down            5
Name: count, dtype: int64

In [612]:
df_2000_good.loc[df_2000_good['безработица'] == 'не указано', 'безработица'] = 'not stated'

In [613]:
df_2000_good['безработица'].value_counts()

безработица
not stated    855
up             10
down            5
Name: count, dtype: int64

In [614]:
## капитал
df_2000_good['капитал'].value_counts()

капитал
not stated                                                                          680
up                                                                                   75
down                                                                                 65
не указано                                                                           48
up», поскольку сделка увеличит долю РусАгро на рынке и расширит географию продаж      1
down»,                                                                                1
Name: count, dtype: int64

In [615]:
df_2000_good.loc[df_2000_good['капитал'] == 'не указано', 'капитал'] = 'not stated'

df_2000_good.loc[df_2000_good['капитал'] == 'down»,', 'капитал'] = 'down'
df_2000_good.loc[df_2000_good['капитал'] == 'up», поскольку сделка увеличит долю РусАгро на рынке и расширит географию продаж', 'капитал'] = 'up'

In [616]:
df_2000_good['капитал'].value_counts()

капитал
not stated    728
up             76
down           66
Name: count, dtype: int64

In [617]:
df_2000_good['капитал'].value_counts()

капитал
not stated    728
up             76
down           66
Name: count, dtype: int64

In [618]:
# инвестиции
df_2000_good['инвестиции'].value_counts()

инвестиции
not stated                                                                                                 711
down                                                                                                        68
не указано                                                                                                  51
up                                                                                                          38
down», возможное up                                                                                          1
up», так как приобретение требует капитальных вложений и расширения производственных мощностей компании      1
Name: count, dtype: int64

In [619]:
df_2000_good.loc[df_2000_good['инвестиции'] == 'не указано', 'инвестиции'] = 'not stated'

df_2000_good.loc[df_2000_good['инвестиции'] == 'down», возможное up', 'инвестиции'] = 'down'
df_2000_good.loc[df_2000_good['инвестиции'] == 'up», так как приобретение требует капитальных вложений и расширения производственных мощностей компании', 'инвестиции'] = 'up'

In [620]:
df_2000_good['инвестиции'].value_counts()

инвестиции
not stated    762
down           69
up             39
Name: count, dtype: int64

In [ ]:
# производство
df_2000_good['производство'].value_counts()

производство
not stated                        646
down                              111
up                                 58
не указано                         54
up», (рост цен на нефть и газ)      1
Name: count, dtype: int64

In [622]:
df_2000_good.loc[df_2000_good['производство'] == 'не указано', 'производство'] = 'not stated'
df_2000_good.loc[df_2000_good['производство'] == 'up», (рост цен на нефть и газ)', 'производство'] = 'up'

In [623]:
df_2000_good['производство'].value_counts()

производство
not stated    700
down          111
up             59
Name: count, dtype: int64

In [624]:
# потребление
df_2000_good['потребление'].value_counts()

потребление
not stated    753
не указано     54
down           43
up             20
Name: count, dtype: int64

In [625]:
df_2000_good.loc[df_2000_good['потребление'] == 'не указано', 'потребление'] = 'not stated'

In [626]:
df_2000_good['потребление'].value_counts()

потребление
not stated    807
down           43
up             20
Name: count, dtype: int64

In [627]:
# численность рабочей силы
df_2000_good['численность рабочей силы'].value_counts()

численность рабочей силы
not stated    804
не указано     55
down            8
up              3
Name: count, dtype: int64

In [628]:
df_2000_good.loc[df_2000_good['численность рабочей силы'] == 'не указано', 'численность рабочей силы'] = 'not stated'

In [629]:
df_2000_good['численность рабочей силы'].value_counts()

численность рабочей силы
not stated    859
down            8
up              3
Name: count, dtype: int64

In [630]:
# сбережения
df_2000_good['сбережения'].value_counts()

сбережения
not stated    790
не указано     55
up             19
down            6
Name: count, dtype: int64

In [631]:
df_2000_good.loc[df_2000_good['сбережения'] == 'не указано', 'сбережения'] = 'not stated'

In [632]:
df_2000_good['сбережения'].value_counts()

сбережения
not stated    845
up             19
down            6
Name: count, dtype: int64

In [633]:
# заработные платы
df_2000_good['заработные платы'].value_counts()

заработные платы
not stated    782
не указано     55
down           23
up             10
Name: count, dtype: int64

In [634]:
df_2000_good.loc[df_2000_good['заработные платы'] == 'не указано', 'заработные платы'] = 'not stated'

In [635]:
df_2000_good['заработные платы'].value_counts()

заработные платы
not stated    837
down           23
up             10
Name: count, dtype: int64

In [637]:
# доходы населения
df_2000_good['доходы населения'].value_counts()

доходы населения
not stated    752
не указано     55
down           45
up             18
Name: count, dtype: int64

In [638]:
df_2000_good.loc[df_2000_good['доходы населения'] == 'не указано', 'доходы населения'] = 'not stated'

In [639]:
df_2000_good['доходы населения'].value_counts()

доходы населения
not stated    807
down           45
up             18
Name: count, dtype: int64

In [640]:
# валютный курс
df_2000_good['валютный курс'].value_counts()

валютный курс
not stated                                               651
up                                                       104
down                                                      61
не указано                                                48
parity reached                                             1
не определено»                                             1
up» (рубль ослабевает)                                     1
up» (курс рубля укрепляется относительно евро и юаня)      1
mixed                                                      1
не указано, вероятно down                                  1
Name: count, dtype: int64

In [641]:
df_2000_good.loc[df_2000_good['валютный курс'] == 'не указано', 'валютный курс'] = 'not stated'
df_2000_good.loc[df_2000_good['валютный курс'] == 'не определено»', 'валютный курс'] = 'not stated'
df_2000_good.loc[df_2000_good['валютный курс'] == 'не указано, вероятно down', 'валютный курс'] = 'not stated'
df_2000_good.loc[df_2000_good['валютный курс'] == 'parity reached', 'валютный курс'] = 'not stated'
df_2000_good.loc[df_2000_good['валютный курс'] == 'mixed', 'валютный курс'] = 'not stated'

df_2000_good.loc[df_2000_good['валютный курс'] == 'up» (рубль ослабевает)', 'валютный курс'] = 'up'
df_2000_good.loc[df_2000_good['валютный курс'] == 'up» (курс рубля укрепляется относительно евро и юаня)', 'валютный курс'] = 'down'

In [642]:
df_2000_good['валютный курс'].value_counts()

валютный курс
not stated    703
up            105
down           62
Name: count, dtype: int64

In [643]:
# импорт
df_2000_good['импорт'].value_counts()

импорт
not stated    733
down           55
не указано     54
up             28
Name: count, dtype: int64

In [644]:
df_2000_good.loc[df_2000_good['импорт'] == 'не указано', 'импорт'] = 'not stated'

In [645]:
df_2000_good['импорт'].value_counts()

импорт
not stated    787
down           55
up             28
Name: count, dtype: int64

In [646]:
# экспорт
df_2000_good['экспорт'].value_counts()

экспорт
not stated                                                                                          674
up                                                                                                   76
down                                                                                                 62
не указано                                                                                           54
не указано, возможно down                                                                             1
up» (рост экспортных цен на сырье)                                                                    1
up», расширение доли на международном рынке благодаря усилению присутствия на масложировом рынке      1
up (кратковременно)                                                                                   1
Name: count, dtype: int64

In [647]:
df_2000_good.loc[df_2000_good['экспорт'] == 'не указано', 'экспорт'] = 'not stated'
df_2000_good.loc[df_2000_good['экспорт'] == 'не указано, возможно down', 'экспорт'] = 'not stated'


df_2000_good.loc[df_2000_good['экспорт'] == 'up» (рост экспортных цен на сырье)'] = 'up'
df_2000_good.loc[df_2000_good['экспорт'] == 'up», расширение доли на международном рынке благодаря усилению присутствия на масложировом рынке'] = 'up'
df_2000_good.loc[df_2000_good['экспорт'] == 'up (кратковременно)'] = 'up'

In [ ]:
df_2000_good['экспорт'].value_counts()

экспорт
not stated    729
up             79
down           62
Name: count, dtype: int64

In [649]:
# государственные расходы
df_2000_good['государственные расходы'].value_counts()

государственные расходы
not stated            789
не указано             54
up                     25
некоторое снижение      1
down                    1
Name: count, dtype: int64

In [650]:
df_2000_good.loc[df_2000_good['государственные расходы'] == 'не указано', 'государственные расходы'] = 'not stated'
df_2000_good.loc[df_2000_good['государственные расходы'] == 'некоторое снижение', 'государственные расходы'] = 'down'

In [651]:
df_2000_good['государственные расходы'].value_counts()

государственные расходы
not stated    843
up             25
down            2
Name: count, dtype: int64

In [652]:
# государственный долг
df_2000_good['государственный долг'].value_counts()

государственный долг
not stated    787
не указано     54
up             25
down            4
Name: count, dtype: int64

In [653]:
df_2000_good.loc[df_2000_good['государственный долг'] == 'не указано', 'государственный долг'] = 'not stated'

In [654]:
df_2000_good['государственный долг'].value_counts()

государственный долг
not stated    841
up             25
down            4
Name: count, dtype: int64

In [655]:
# дефицит бюджета
df_2000_good['дефицит бюджета'].value_counts()

дефицит бюджета
not stated    774
не указано     54
up             38
down            3
сокращение      1
Name: count, dtype: int64

In [656]:
df_2000_good.loc[df_2000_good['дефицит бюджета'] == 'не указано', 'дефицит бюджета'] = 'not stated'
df_2000_good.loc[df_2000_good['дефицит бюджета'] == 'сокращение', 'дефицит бюджета'] = 'down'

In [657]:
df_2000_good['дефицит бюджета'].value_counts()

дефицит бюджета
not stated    828
up             38
down            4
Name: count, dtype: int64

In [658]:
## инфляция
df_2000_good['инфляция'].value_counts()

инфляция
not stated    654
up            117
не указано     50
down           49
Name: count, dtype: int64

In [659]:
df_2000_good.loc[df_2000_good['инфляция'] == 'не указано', 'инфляция'] = 'not stated'

In [660]:
df_2000_good['инфляция'].value_counts()

инфляция
not stated    704
up            117
down           49
Name: count, dtype: int64

In [661]:
df_2000_good.shape

(870, 21)

In [662]:
df_1000_good.shape

(515, 21)

In [663]:
df_2000_all = pd.concat([df_1000_all, df_2000_good], axis=0)
df_2000_all

,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,потребление,численность рабочей силы,сбережения,...,доходы населения,валютный курс,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета,doc_id,chunk_id,original_text
0,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1,0,"""Индекс Мосбиржи -3%. Это самое большое дневно..."
1,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,2,0,"""​​Циан взлетел на апелляции Крупнейший в Росс..."
2,not stated,down,up,not stated,not stated,not stated,down,not stated,not stated,not stated,...,down,not stated,not stated,down,not stated,not stated,up,2,1,"""С 5 февраля ЕС вводит эмбарго на российские п..."
3,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,up,3,0,Госбюджет РФ рискует недополучить еще больше н...
4,not stated,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,4,0,"""Новый отчёт Сбера (SBER): чистая прибыль за 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1488,0,• Объем торгов металлами в феврале составил 61...
946,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1489,0,"""​​Страхованию инвестиций на ИИС — быть В дека..."
947,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,up,not stated,not stated,not stated,not stated,not stated,1489,1,"""​​Что означает 100 рублей за доллар для префо..."
948,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,up,not stated,not stated,not stated,not stated,not stated,1491,0,В начале октября валютный курс тестирует сопро...
949,not stated,down,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,...,not stated,up,up,down,not stated,not stated,not stated,1491,4,"""Финансовый конгресс Банка России: что важного..."

In [664]:
df_2000_all.to_csv('df_2000_all_new.csv', index=False)