In [1]:
!pip install --upgrade transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.6.2-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.10.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.6.2-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 98.9 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.6.2

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import pandas as pd
import json
import re

## ПРОВЕРИМ ТОЧНОСТЬ НА ТЕСТОВОМ ДАТАСЕТЕ БЕЗ ДООБУЧЕНИЯ

In [3]:
data_2000 = pd.read_csv("df_2000_all_new.csv")
data_2000

,процентная ставка,ВВП,инфляция,безработица,капитал,инвестиции,производство,потребление,численность рабочей силы,сбережения,...,доходы населения,валютный курс,импорт,экспорт,государственные расходы,государственный долг,дефицит бюджета,doc_id,chunk_id,original_text
0,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1,0,"""Индекс Мосбиржи -3%. Это самое большое дневно..."
1,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,2,0,"""​​Циан взлетел на апелляции Крупнейший в Росс..."
2,not stated,down,up,not stated,not stated,not stated,down,not stated,not stated,not stated,...,down,not stated,not stated,down,not stated,not stated,up,2,1,"""С 5 февраля ЕС вводит эмбарго на российские п..."
3,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,up,3,0,Госбюджет РФ рискует недополучить еще больше н...
4,not stated,not stated,not stated,not stated,up,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,4,0,"""Новый отчёт Сбера (SBER): чистая прибыль за 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1488,0,• Объем торгов металлами в феврале составил 61...
1802,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,not stated,not stated,not stated,not stated,not stated,not stated,1489,0,"""​​Страхованию инвестиций на ИИС — быть В дека..."
1803,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,up,not stated,not stated,not stated,not stated,not stated,1489,1,"""​​Что означает 100 рублей за доллар для префо..."
1804,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,not stated,...,not stated,up,not stated,not stated,not stated,not stated,not stated,1491,0,В начале октября валютный курс тестирует сопро...
1805,not stated,down,not stated,not stated,not stated,not stated,down,not stated,not stated,not stated,...,not stated,up,up,down,not stated,not stated,not stated,1491,4,"""Финансовый конгресс Банка России: что важного..."

In [4]:
## ТУТ ТОЖЕ КОСЯКА НЕ БЫЛО)
data_2000 = data_2000[data_2000['doc_id'] != 'up']
data_2000['doc_id'] = data_2000['doc_id'].astype('int')

test = data_2000[(data_2000['doc_id'] > 1234)]

/tmp/ipykernel_1244/733867683.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_2000['doc_id'] = data_2000['doc_id'].astype('int')

In [5]:
dataset = list(test['original_text'])

## ТЕСТ МОДЕЛИ БЕЗ ОБУЧЕНИЯ

In [6]:
model_name = "Qwen/Qwen2.5-7B-Instruct"

# Загрузка токенизатора и модели
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16, # или torch.float16
    device_map="auto"           # автоматически распределит веса на GPU
)

responces = []
with torch.no_grad():
    for i, text in enumerate(dataset, 1):
        print(f'Обработка документа {i}...')


        prompt = ( "Твоя задача — анализировать новости "
        "и определять динамику 18 показателей. Оценивай прямые упоминания и логические следствия. "
        "Допустимые значения изменений ТОЛЬКО ТАКИЕ: 'up', 'down', 'not stated'. "
        "Ответь строго в формате JSON без вступлений и пояснений: "
        "{"
        "\"процентная ставка\": \"тип изменения\","
        "\"ВВП\": \"тип изменения\","
        "\"инфляция\": \"тип изменения\","
        "\"безработица\": \"тип изменения\","
        "\"капитал\": \"тип изменения\","
        "\"инвестиции\": \"тип изменения\","
        "\"производство\": \"тип изменения\","
        "\"потребление\": \"тип изменения\","
        "\"численность рабочей силы\": \"тип изменения\","
        "\"сбережения\": \"тип изменения\","
        "\"заработные платы\": \"тип изменения\","
        "\"доходы населения\": \"тип изменения\","
        "\"валютный курс\": \"тип изменения\","
        "\"импорт\": \"тип изменения\","
        "\"экспорт\": \"тип изменения\","
        "\"государственные расходы\": \"тип изменения\","
        "\"государственный долг\": \"тип изменения\","
        "\"дефицит бюджета\": \"тип изменения\""
        "} "
        f"Текст новости: {text}"
    )
        messages = [
            {"role": "system", "content": "Ты — экспертный макроэкономический аналитик."},
            {"role": "user", "content": prompt}
        ]

        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=512
        )
        generated_ids = [
            output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
        ]
        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
        responces.append(response)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Обработка документа 1...
Обработка документа 2...
Обработка документа 3...
Обработка документа 4...
Обработка документа 5...
Обработка документа 6...
Обработка документа 7...
Обработка документа 8...
Обработка документа 9...
Обработка документа 10...
Обработка документа 11...
Обработка документа 12...
Обработка документа 13...
Обработка документа 14...
Обработка документа 15...
Обработка документа 16...
Обработка документа 17...
Обработка документа 18...
Обработка документа 19...
Обработка документа 20...
Обработка документа 21...
Обработка документа 22...
Обработка документа 23...
Обработка документа 24...
Обработка документа 25...
Обработка документа 26...
Обработка документа 27...
Обработка документа 28...
Обработка документа 29...
Обработка документа 30...
Обработка документа 31...
Обработка документа 32...
Обработка документа 33...
Обработка документа 34...
Обработка документа 35...
Обработка документа 36...
Обработка документа 37...
Обработка документа 38...
Обработка документа 39...
Обработка документа 40...
Обработка документа 41...
Обработка документа 42...
Обработка документа 43...
Обработка документа 44...
Обработка документа 45...
Обработка документа 46...
Обработка документа 47...
Обработка документа 48...
Обработка документа 49...
Обработка документа 50...
Обработка документа 51...
Обработка документа 52...
Обработка документа 53...
Обработка документа 54...
Обработка документа 55...
Обработка документа 56...
Обработка документа 57...
Обработка документа 58...
Обработка документа 59...
Обработка документа 60...
Обработка документа 61...
Обработка документа 62...
Обработка документа 63...
Обработка документа 64...
Обработка документа 65...
Обработка документа 66...
Обработка документа 67...
Обработка документа 68...
Обработка документа 69...
Обработка документа 70...
Обработка документа 71...
Обработка документа 72...
Обработка документа 73...
Обработка документа 74...
Обработка документа 75...
Обработка документа 76...
Обработка документа 77...
Обработка документа 78...
Обработка документа 79...
Обработка документа 80...
Обработка документа 81...
Обработка документа 82...
Обработка документа 83...
Обработка документа 84...
Обработка документа 85...
Обработка документа 86...
Обработка документа 87...
Обработка документа 88...
Обработка документа 89...
Обработка документа 90...
Обработка документа 91...
Обработка документа 92...
Обработка документа 93...
Обработка документа 94...
Обработка документа 95...
Обработка документа 96...
Обработка документа 97...
Обработка документа 98...
Обработка документа 99...
Обработка документа 100...
Обработка документа 101...
Обработка документа 102...
Обработка документа 103...
Обработка документа 104...
Обработка документа 105...
Обработка документа 106...
Обработка документа 107...
Обработка документа 108...
Обработка документа 109...
Обработка документа 110...
Обработка документа 111...
Обработка документа 112...
Обработка документа 113...
Обработка документа 114...
Обработка документа 115...
Обработка документа 116...
Обработка документа 117...
Обработка документа 118...
Обработка документа 119...
Обработка документа 120...
Обработка документа 121...
Обработка документа 122...
Обработка документа 123...
Обработка документа 124...
Обработка документа 125...
Обработка документа 126...
Обработка документа 127...
Обработка документа 128...
Обработка документа 129...
Обработка документа 130...
Обработка документа 131...
Обработка документа 132...
Обработка документа 133...
Обработка документа 134...
Обработка документа 135...
Обработка документа 136...
Обработка документа 137...
Обработка документа 138...
Обработка документа 139...
Обработка документа 140...
Обработка документа 141...
Обработка документа 142...
Обработка документа 143...
Обработка документа 144...
Обработка документа 145...
Обработка документа 146...
Обработка документа 147...
Обработка документа 148...
Обработка документа 149...
Обработка документа 150...
Обработка документа 151...
Обработка документа 152...
Обработка документа 153...
Обработка документа 154...
Обработка документа 155...
Обработка документа 156...
Обработка документа 157...
Обработка документа 158...
Обработка документа 159...
Обработка документа 160...
Обработка документа 161...
Обработка документа 162...
Обработка документа 163...
Обработка документа 164...
Обработка документа 165...
Обработка документа 166...
Обработка документа 167...
Обработка документа 168...
Обработка документа 169...
Обработка документа 170...
Обработка документа 171...
Обработка документа 172...
Обработка документа 173...
Обработка документа 174...
Обработка документа 175...
Обработка документа 176...
Обработка документа 177...
Обработка документа 178...
Обработка документа 179...
Обработка документа 180...
Обработка документа 181...
Обработка документа 182...
Обработка документа 183...
Обработка документа 184...
Обработка документа 185...
Обработка документа 186...
Обработка документа 187...
Обработка документа 188...
Обработка документа 189...
Обработка документа 190...
Обработка документа 191...
Обработка документа 192...
Обработка документа 193...
Обработка документа 194...
Обработка документа 195...
Обработка документа 196...
Обработка документа 197...
Обработка документа 198...
Обработка документа 199...
Обработка документа 200...
Обработка документа 201...
Обработка документа 202...
Обработка документа 203...
Обработка документа 204...
Обработка документа 205...
Обработка документа 206...
Обработка документа 207...
Обработка документа 208...
Обработка документа 209...
Обработка документа 210...
Обработка документа 211...
Обработка документа 212...
Обработка документа 213...
Обработка документа 214...
Обработка документа 215...
Обработка документа 216...
Обработка документа 217...
Обработка документа 218...
Обработка документа 219...
Обработка документа 220...
Обработка документа 221...
Обработка документа 222...
Обработка документа 223...
Обработка документа 224...
Обработка документа 225...
Обработка документа 226...
Обработка документа 227...
Обработка документа 228...
Обработка документа 229...
Обработка документа 230...
Обработка документа 231...
Обработка документа 232...
Обработка документа 233...
Обработка документа 234...
Обработка документа 235...
Обработка документа 236...
Обработка документа 237...
Обработка документа 238...
Обработка документа 239...
Обработка документа 240...
Обработка документа 241...
Обработка документа 242...
Обработка документа 243...
Обработка документа 244...
Обработка документа 245...
Обработка документа 246...
Обработка документа 247...
Обработка документа 248...
Обработка документа 249...
Обработка документа 250...
Обработка документа 251...
Обработка документа 252...
Обработка документа 253...
Обработка документа 254...
Обработка документа 255...
Обработка документа 256...
Обработка документа 257...
Обработка документа 258...
Обработка документа 259...
Обработка документа 260...
Обработка документа 261...
Обработка документа 262...
Обработка документа 263...
Обработка документа 264...
Обработка документа 265...
Обработка документа 266...
Обработка документа 267...
Обработка документа 268...

In [7]:
## СОХРАРНИМ РЕЗУЛЬТАТЫ НЕ ОБУЧЕННОГО КВЕНА
df_qwen_untr = [{'responce': responces[i], 'doc_id': test.iloc[i, -3],
      'chunk_id': test.iloc[i, -2], 'original_text': test.iloc[i, -1]} for i in range(len(responces))]
df_qwen_untr = pd.DataFrame(df_qwen_untr)
df_qwen_untr

,responce,doc_id,chunk_id,original_text
0,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1236,0,"В СМИ звучали предположения, что они имели отн..."
1,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1238,0,"""​​Продажа Яндекса: чего ждать держателям акци..."
2,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1239,0,"""Топ-30 российских компаний по капитализации. ..."
3,"{""процентная ставка"": ""up"",""ВВП"": ""not stated""...",1239,1,"""​​Рынки обеспокоены растущими ценами на нефть..."
4,"```json\n{""процентная ставка"": ""not stated"",""В...",1239,2,• Рынки Азиатско-Тихоокеанского региона демонс...
...,...,...,...,...
263,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1488,0,• Объем торгов металлами в феврале составил 61...
264,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1489,0,"""​​Страхованию инвестиций на ИИС — быть В дека..."
265,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1489,1,"""​​Что означает 100 рублей за доллар для префо..."
266,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1491,0,В начале октября валютный курс тестирует сопро...
267,"{""процентная ставка"": ""not stated"",""ВВП"": ""not...",1491,4,"""Финансовый конгресс Банка России: что важного..."

In [8]:
df_qwen_untr.to_csv('df_qwen_untr_test.csv', index=False)

In [12]:
df_to_check = test
# ------------------------------------------

expected_keys = [
    "процентная ставка", "ВВП", "инфляция", "безработица", "капитал",
    "инвестиции", "производство", "потребление", "численность рабочей силы",
    "сбережения", "заработные платы", "доходы населения", "валютный курс",
    "импорт", "экспорт", "государственные расходы", "государственный долг",
    "дефицит бюджета"
]

total_accuracy = 0
valid_json_count = 0
up_down_accuracy = 0
k = len(responces) # Берем по количеству реально полученных ответов

not_up_down = 0

print("--- Начинаю робастный расчет метрик ---")

for i, pred_raw in enumerate(responces):
    try:
        clean_pred = pred_raw.strip()
        json_match = re.search(r'\{.*\}', clean_pred, re.DOTALL)

        if not json_match:
            print(f"Документ {i+1}: JSON не найден в тексте")
            continue

        pred_json = json.loads(json_match.group())

        correct_in_doc = 0
        correct_in_doc_up_down = 0
        cur_up_down_ans = 0
        for entity in expected_keys:
            # ответ модели
            model_val = str(pred_json.get(entity, "missing")).lower().strip()


            true_val = str(df_to_check.iloc[i][entity]).lower().strip()

            if model_val == true_val:
                correct_in_doc += 1

            ## отдельно считаем метрики для not_stated(ЕСТЬ ДИЗБАЛАНС КЛАССОВ)
            if true_val != 'not stated':
                cur_up_down_ans += 1
                if model_val == true_val:
                    correct_in_doc_up_down += 1
        ## ПРОВЕРЯЕМ ЕСТЬ ЛИ ХОТЯ БЫ ОДИН UP/DOWN В ОТВЕТАХ
        if cur_up_down_ans != 0:
            up_down_accuracy += correct_in_doc_up_down / cur_up_down_ans
        else:
            ## СЧИТАЕМ ЧИСЛО ПРАВИЛЬНЫХ ОТВЕТОВ ГДЕ ВСЕХ СУЩНОСТЕЙ НЕТ
            not_up_down += 1

        total_accuracy += (correct_in_doc / len(expected_keys))

        valid_json_count += 1

    except json.JSONDecodeError:
        print(f"Документ {i+1}: Ошибка декодирования JSON")
    except KeyError as e:
        print(f"Документ {i+1}: В датафрейме нет колонки {e}")
    except Exception as e:
        print(f"Документ {i+1}: Непредвиденная ошибка {type(e).__name__}: {e}")

final_accuracy = total_accuracy / k if k > 0 else 0
accuracy_up_down = up_down_accuracy / (k - not_up_down)

print("-" * 30)
print(f"ИТОГОВАЯ ACCURACY: {final_accuracy:.4f}")
print(f"ИТОГОВАЯ ACCURACY НА ПРИМЕРАХ UP/DOWN: {accuracy_up_down:.4f}")


print(f"Успешно обработано: {valid_json_count} из {k}")

--- Начинаю робастный расчет метрик ---
------------------------------
ИТОГОВАЯ ACCURACY: 0.9177
ИТОГОВАЯ ACCURACY НА ПРИМЕРАХ UP/DOWN: 0.5185
Успешно обработано: 268 из 268

## КАЧЕСТВО УЖЕ НЕПЛОХОЕ 92% на ВСЕХ ПРИМЕРАХ И 52% НА ПРИМЕРАХ С ИЗМЕНЕНИЯМИ, НО МЫ ХОТИМ ЛУЧШЕ

---